### ISSUE TITLE
Fault tolerance support

### ISSUE THREAD

**Issue by yingfeng** [DTStack/flinkx#10]
Does this project support fault tolerance? 
Suppose an ETL job is running, if some nodes corrupted, the data transfer should be guaranteed without any data loss or data duplication, that's some kinds of transaction. Using Flink as a building block for ETL is a good idea, however, providing such features are non-trival, does Flinkx support this?

**Comment by yangsishu** [comment]
now does not support this

**Comment by yangsishu** [comment]
Now I'm doing a breakpoint continuation
