### ISSUE TITLE
yarnPer模式，推荐上传全部jar包，而不是仅上传core包，通过classpath去导入插件包

### ISSUE THREAD

**Issue by mosence** [DTStack/flinkx#103]
在yarnPer模式，目前仅仅上传flink自身包以及flinkx-core包，插件包没有上传，导致yarn-node上如果没有部署flinkx就会报class notfound异常
推荐在
```
JobGraph jobGraph = PackagedProgramUtils.createJobGraph(program, conf, Integer.parseInt(launcherOptions.getParallelism()));
```
之后把所有插件包添加进去
```
for(URL classPathUrl: urlList){
  jobGraph.addJar(new Path(classPathUrl.toString()));
}
```

**Comment by kanata163** [comment]
目前确实是这样的，需要在node节点上部署flinkx插件包。你说的这个问题我们当初也考虑过，当插件包体积比较小，这样做无疑是非常便捷的。但是随着数据源数量增多，插件包体积越来越大，每次yarnPer上传一大堆插件包就会耗费很长时间。

**Comment by mosence** [comment]
那么请问下能不能用 hdfs://pluginsPath/ 之类的公共存储指定插件目录？否则yarn node节点非常多的情况下还需要统一去管理这些插件包就很难受。
