### ISSUE TITLE
能否在idea中提交yarnPer模式

### ISSUE THREAD

**Issue by LoveXiaoQuan** [DTStack/flinkx#107]

**Comment by kanata163** [comment]
可以 
启动参数参考
-job
/Users/aaa.json
-pluginRoot
/opt/dtstack/180_flinkplugin/syncplugin
-flinkconf
/opt/dtstack/flink-1.8.1/conf
-yarnconf
/opt/dtstack/hadoop-2.7.3/etc/hadoop
-flinkLibJar
/opt/dtstack/flink-1.8.1/lib
-confProp
{\"mr.job.parallelism\":1,\"sql.checkpoint.interval\":60000,\"sql.env.parallelism\":1,\"jobmanager.memory.mb\":1276,\"taskmanager.memory.mb\":1276,\"taskmanager.num\":2,\"taskmanager.slots\":2,\"jobmanager.archive.fs.dir\":\"hdfs://ns1/flink180/completed-jobs_1\"}
-queue
c
