### ISSUE TITLE
mysql to hive  这里代码是不是有问题

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkx#110]
obj != null && obj instanceof Map  为啥是map ?

  
@Override
    public void writeRecord(Row row) throws IOException {
        try {
            if (row.getArity() == 2) {
                Object obj = row.getField(0);
                if (obj != null && obj instanceof Map) {
                    emitWithMap((Map<String, Object>) obj, row);
                }
            } else {
                emitWithRow(row);
            }
        } catch (Throwable e) {
            logger.error("{}", e);
        }
    }

**Comment by kanata163** [comment]
这是为了兼容binlong和kafka过来的map数据
