### ISSUE TITLE
idea提交yarnPer模式失败

### ISSUE THREAD

**Issue by LoveXiaoQuan** [DTStack/flinkx#111]
参数：
-mode yarnPer -job D:\桌面\kafka10_to_hbase.json -pluginRoot D:\workspace\flinkx\plugins -flinkconf D:\桌面\flinkconf -yarnconf D:\桌面\yarnconf
-confProp {} -flinkLibJar D:\桌面\flinklib
报错
Error: Could not find or load main class org.apache.flink.yarn.entrypoint.YarnJobClusterEntrypoint
在服务器上远程提交可以实现，但是idea里一直不行，麻烦指点下

**Comment by kanata163** [comment]
-pluginRoot D:\workspace\flinkx\plugins 
-flinkconf D:\桌面\flinkconf 
-yarnconf D:\桌面\yarnconf
-flinkLibJar D:\桌面\flinklib
以yarnPer模式运行，在运行节点上也必须存在对应的目录及文件，
你这里应该是这些路径下面缺东西

**Comment by LoveXiaoQuan** [comment]
你好，但是我在linux的环境下，可以远程提交，我的运行节点上并没有部署flinkx程序------------------ 原始邮件 ------------------
发件人: "kanata163"<notifications@github.com>
发送时间: 2019年11月11日(星期一) 晚上9:46
收件人: "DTStack/flinkx"<flinkx@noreply.github.com>;
抄送: "LoveXiaoQuan"<1119593634@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DTStack/flinkx] idea提交yarnPer模式失败 (#111)



-pluginRoot D:\workspace\flinkx\plugins
 -flinkconf D:\桌面\flinkconf
 -yarnconf D:\桌面\yarnconf
 -flinkLibJar D:\桌面\flinklib
 以yarnPer模式运行，在运行节点上也必须存在对应的目录及文&#x4EF6;，
 你这里应该是这些路径下面缺东西
 
&mdash;

**Comment by kanata163** [comment]
我不清楚你在Linux环境是如何能够远程提交的，你先在你的本地环境检查下相应的路径下和Linux环境下的jar包是否是一致的。然后再试试，如果还是报错，请贴出完整的错误信息。

**Comment by todd5167** [comment]
@LoveXiaoQuan   window系统的IDEA提交不上去的

**Comment by pecanNBU** [comment]
这个问题有什么好的解决办法吗？

**Comment by yeweicheng** [comment]
windows的classpath是分号，linux是冒号，在win idea提交的时候container的启动脚本是有问题的，加载不了jar

**Comment by ZChanghai** [comment]
@kanata163 这个问题有什么好的办法解决吗？

**Comment by ZChanghai** [comment]
这个问题应该和官网上报的是一个问题
https://issues.apache.org/jira/browse/FLINK-17858
