### ISSUE TITLE
数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？

### ISSUE THREAD

**Issue by OwnLifeDancer** [DTStack/flinkx#113]
数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？

**Comment by kanata163** [comment]
首先在你配置的path目录下创建一个.data文件夹，然后将kafka传过来的数据临时保存在.data文件夹下的临时文件中。当任务结束或者触发checkpoint的时候，将这些临时文件移动到正式的path目录下。

**Comment by OwnLifeDancer** [comment]
在什么时候任务结束呢？因为源是从kafka中读取的，正常情况就是这个reader并不会一次性消费，会一直保持连接状态，那这个任务就不会结束。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午2:00
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"舞者莫於狐"<540746457@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] 数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？ (#113)



首先在你配置的path目录下创建一个.data文件夹，然后将kafka传过来的数据临时保存在.data文件夹下的临时文件中。当任务结束或者触发checkpoint的时候，将这些临时文件移动到正式的path目录下。

**Comment by kanata163** [comment]
实时采集只能手动去取消任务才会结束

**Comment by OwnLifeDancer** [comment]
比如在idea中我手动停止stop run程序就可以停止还是需要怎样停止呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午2:11
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"舞者莫於狐"<540746457@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] 数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？ (#113)



实时采集只能手动去取消任务才会结束

**Comment by kanata163** [comment]
idea里面stop run就直接干掉进程了，你需要去flink dashboard里面点cancel按钮取消

**Comment by OwnLifeDancer** [comment]
目前只用到flinkx工具，并没有flink集群，在flinkx中有没有对应的接口或者方法呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午2:14
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"舞者莫於狐"<540746457@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] 数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？ (#113)



idea里面stop run就直接干掉进程了，你需要去flink dashboard里面点cancel按钮取消

**Comment by kanata163** [comment]
idea本地运行也是可以使用flink dashboard的，具体教程你自己百度吧。

**Comment by OwnLifeDancer** [comment]
想了解下在flinkx中有没有可以停止job的接口或调用方法，如果没有我想自己添加一个这样的功能有没有具体方法呀。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午2:26
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"舞者莫於狐"<540746457@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] 数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？ (#113)



idea本地运行也是可以使用flink dashboard的，具体教程你自己百度吧。

**Comment by kanata163** [comment]
flinkx里面目前是没有的，你想做可以参考https://ci.apache.org/projects/flink/flink-docs-release-1.8/monitoring/rest_api.html的mode (optional): String value that specifies the termination mode. Supported values are: "cancel, stop".

**Comment by OwnLifeDancer** [comment]
想问下这个invoke()方法在什么时候被调用？DeBug了一遍也没发现是在哪里调用的，求解答？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 下午4:45
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"舞者莫於狐"<540746457@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] 数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？ (#113)



flinkx里面目前是没有的，你想做可以参考https://ci.apache.org/projects/flink/flink-docs-release-1.8/monitoring/rest_api.html的mode (optional): String value that specifies the termination mode. Supported values are: "cancel, stop".

**Comment by kanata163** [comment]
哪个invoke()?

**Comment by OwnLifeDancer** [comment]
抱歉，上次发的邮件，用的截图在github上看不到。我这再描述一下：org.apache.flink.streaming.api.functions.sink.DtOutputFormatSinkFunction这个类里面的invoke()方法，因为看了下，感觉在local模式下往FTP输出流写数据要通过这个方法。请指点下。

**Comment by kanata163** [comment]
![image](https://user-images.githubusercontent.com/35188210/68913014-e6fb3b00-0794-11ea-9acb-a1e645289805.png)

你任务运行的时候没往kafka里面打数据吧

**Comment by OwnLifeDancer** [comment]
生产新的数据进去了，flinkx也已经读取到数据，但是没有写入FTP，而且我把写入数据那块的策略改成，每写一条就flush。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月15日(星期五) 上午10:46
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"舞者莫於狐"<540746457@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] 数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？ (#113)



 你任务运行的时候没往kafka里面打数据吧

**Comment by OwnLifeDancer** [comment]
目前我玩的情况是这样：kafka_to_ftp现在调通了，但是换成sqlserver_to_ftp就写不通了，打断点发现不走invoke方法。

**Comment by kanata163** [comment]
你自己再看下吧，没调invoke说明没有数据写进来。

**Comment by OwnLifeDancer** [comment]
数据应该写到哪块呢？找了很长时间没找到？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kanata163"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月15日(星期五) 中午11:23
收件人:&nbsp;"DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送:&nbsp;"舞者莫於狐"<540746457@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DTStack/flinkx] 数据从kafka读取写入到ftp，FTP写入时的过程是什么样的？ (#113)



你自己再看下吧，没调invoke说明没有数据写进来。

**Comment by OwnLifeDancer** [comment]
目前发现一个问题：sqlserver_to_mysql是可以实现的，但是sqlserver_to_ftp不通是因为目前不支持这种方式吗？求助帮忙看下，看代码没发现什么问题。

**Comment by kanata163** [comment]
你用1.8.2分支，我刚才跑了一个SqlServer到FTP，能成功。

**Comment by OwnLifeDancer** [comment]
我用最新的1.8.2分支跑了下还是不行，能把配置文件共享一下吗？

**Comment by kanata163** [comment]
{
  "job" : {
    "content" : [ {
      "reader" : {
        "parameter" : {
          "password" : "paswsword",
          "customSql" : "",
          "startLocation" : "",
          "increColumn" : "",
          "column" : [ {
            "name" : "id",
            "type" : "bigint",
            "key" : "id"
          }, {
            "name" : "user_id",
            "type" : "bigint",
            "key" : "user_id"
          }, {
            "name" : "name",
            "type" : "varchar",
            "key" : "name"
          } ],
          "connection" : [ {
            "password" : "paswsword",
            "jdbcUrl" : [ "jdbc:jtds:sqlserver://0.0.0.0:1433;DatabaseName=databaseName" ],
            "table" : [ "table" ],
            "username" : "username"
          } ],
          "username" : "username"
        },
        "name" : "sqlserverreader"
      },
      "writer" : {
        "parameter" : {
          "path" : "/opt/dtstack",
          "protocol" : "sftp",
          "password" : "password",
          "port" : 22,
          "host" : "0.0.0.0",
          "column" : [ {
            "name" : "id",
            "type" : "bigint",
            "key" : "id"
          }, {
            "name" : "user_id",
            "type" : "bigint",
            "key" : "user_id"
          }, {
            "name" : "name",
            "type" : "varchar",
            "key" : "name"
          } ],
          "writeMode" : "APPEND",
          "fieldDelimiter" : ",",
          "encoding" : "utf-8",
          "username" : "username"
        },
        "name" : "ftpwriter"
      }
    } ],
    "setting" : {
      "restore" : {
        "maxRowNumForCheckpoint" : 0,
        "isRestore" : false,
        "restoreColumnName" : "",
        "restoreColumnIndex" : 0
      },
      "errorLimit" : {
        "record" : 100
      },
      "speed" : {
        "bytes" : 0,
        "channel" : 1
      }
    }
  }
}
