### ISSUE TITLE
数据同步到hive 了 但是 是在隐藏目录下面， 而且是随机的

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkx#115]
drwxrwxrwx   - bozhong admin          0 2019-11-12 21:02 /user/hive/warehouse/test_flink2211/pt=2019111221/.data
drwxrwxrwx   - bozhong admin          0 2019-11-12 21:02 /user/hive/warehouse/test_flink2211/pt=2019111221/.finished

**Comment by kanata163** [comment]
.data和.finished是临时目录，数据文件是先写入到.data目录下，然后再移动到
/user/hive/warehouse/test_flink2211/pt=2019111221/这个目录下,你可以看下
moveTemporaryDataBlockFileToDirectory()这个方法

**Comment by maidou75293** [comment]
我明白这个原理，1.为啥没调用呢
2.貌似缓存设置大了，就不刷新出文件了



---原始邮件---
发件人: "kanata163"<notifications@github.com&gt;
发送时间: 2019年11月12日(星期二) 晚上9:52
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkx] 数据同步到hive 了 但是 是在隐藏目录下面， 而且是随机的 (#115)



.data和.finished是临时目录，数据文件是先写入到.data目录下，然后再移动到
 /user/hive/warehouse/test_flink2211/pt=2019111221/这个目录下,你可以看下
 moveTemporaryDataBlockFileToDirectory()这个方法

**Comment by a2236802667** [comment]
我也遇到了这个问题，你解决了吗？
