### ISSUE TITLE
writeMultipleRecordsInternal

### ISSUE THREAD

**Issue by pierre94** [DTStack/flinkx#122]
咨询一下什么时候会调用这个函数呢

**Comment by kanata163** [comment]
你先看下面的执行流程
`DtOutputFormatSinkFunction.invoke()`
->
`RichOutputFormat.writeRecord()`
->
`RichOutputFormat.writeRecordInternal()`

当outputformat中的batchInterval>1时，就会调`writeMultipleRecordsInternal()`
不同数据源batchInterval设置不同，并且有些数据源不支持`writeMultipleRecordsInternal()`

**Comment by pierre94** [comment]
明白了。
自定义Writer类时，在writeData方法构建builder的时候需要
```java
builder.setBatchInterval(batchInterval);
```
当batchInterval > 1时就会调用OutoutFormat的writeMultipleRecordsInternal。
