### ISSUE TITLE
如何实现mysql增量同步到hive？用了increColumn还是全量方式同步

### ISSUE THREAD

**Issue by mingge12321** [DTStack/flinkx#123]
"reader": {
        "parameter": {
          "username": "xxxx",
          "password": "zxxxx",
          "connection": [{
            "jdbcUrl": [
              "jdbc:mysql://xxx:3306/datacompute2?useCursorFetch=true"
            ],
            "table": [
              "test_flink2212"
            ]
          }],
          "column": [{
            "name": "name",
            "index":1,
            "type": "bigint",
            "values": 123
          },{
            "name":"age",
            "type":"int",
            "value":"22"
          }],
          "where": "name > 1",
          "splitPk": "name",
          "fetchSize": 1000,
          "queryTimeOut": 1000,
          "customSql": "select * from test_flink2212",
          "requestAccumulatorInterval": 5,
          "increColumn": "name",
          "startLocation": null,
          "useMaxFunc": true,
          "orderByColumn": "name"
        },
        "name": "mysqlreader"
      }

**Comment by kanata163** [comment]
![image](https://user-images.githubusercontent.com/35188210/69299364-5a94c080-0c4b-11ea-8b4c-9aacf35026e6.png)

**Comment by maidou75293** [comment]
yarn 模式也有效么， 每次同步到的位置存储在哪里呢

**Comment by kanata163** [comment]
有效。任务结束时会有个endLocation的指标，我们有其他外部应用会获取endLocation然后用于构建下次任务的startlocation。你可通过http://hostname:port/jobs/<jobid>/accumulators去看。

**Comment by maidou75293** [comment]
其他外部应用是啥，我们怎么用这个外部应用



---原始邮件---
发件人: "kanata163"<notifications@github.com&gt;
发送时间: 2019年11月22日(星期五) 中午12:01
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [DTStack/flinkx] 如何实现mysql增量同步到hive？用了increColumn还是全量方式同步 (#123)



有效。任务结束时会有个endLocation的指标，我们有其他外部应用会获取endLocation然后用于构建下次任务的startlocation。你可通过http://hostname:port/jobs//accumulators去看。

**Comment by kanata163** [comment]
公司内部开发的商业应用

**Comment by maidou75293** [comment]
意思是想用要花钱是吧？



---原始邮件---
发件人: "kanata163"<notifications@github.com&gt;
发送时间: 2019年11月22日(星期五) 下午4:08
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [DTStack/flinkx] 如何实现mysql增量同步到hive？用了increColumn还是全量方式同步 (#123)



公司内部开发的商业应用

**Comment by lijiangbo** [comment]
这个项目只提供基础的功能，有些功能需要自己实现
