### ISSUE TITLE
kafka json 结构 怎么映射写到 es里面？

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkx#125]

**Comment by lijiangbo** [comment]
从kafka读取到的消息会存到一个字段里，字段格式为map类型：
[{message=this is message}]
假设es配置的字段为 col1，则写入es的结果为:
{
"col1":"{message=this is message}"
}

**Comment by maidou75293** [comment]
只能整个是一个字段?
我看了源码还行也是只能当成一个字段



---原始邮件---
发件人: "jiangbo"<notifications@github.com&gt;
发送时间: 2019年11月23日(星期六) 中午1:20
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkx] kafka json 结构 怎么映射写到 es里面？ (#125)



从kafka读取到的消息会存到一个字段里，字段格式为map类型：
 [{message=this is message}]
 假设es配置的字段为 col1，则写入es的结果为:
 {
 "col1":"{message=this is message}"
 }

**Comment by maidou75293** [comment]
那没发针对 map元素 建立索引啊



---原始邮件---
发件人: "jiangbo"<notifications@github.com&gt;
发送时间: 2019年11月23日(星期六) 中午1:20
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkx] kafka json 结构 怎么映射写到 es里面？ (#125)



从kafka读取到的消息会存到一个字段里，字段格式为map类型：
 [{message=this is message}]
 假设es配置的字段为 col1，则写入es的结果为:
 {
 "col1":"{message=this is message}"
 }

**Comment by lijiangbo** [comment]
你可以在这基础上进行扩展

**Comment by maidou75293** [comment]
是这么打算的，也纳闷，你们 flinkSQL&nbsp; es 版本为啥 是5 呢



---原始邮件---
发件人: "jiangbo"<notifications@github.com&gt;
发送时间: 2019年11月23日(星期六) 中午1:24
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkx] kafka json 结构 怎么映射写到 es里面？ (#125)



你可以在这基础上进行扩展
