### ISSUE TITLE
Failed to collect dependencies at com.ibm.db2:db2jcc:jar:3.72.44

### ISSUE THREAD

**Issue by geekxingyun** [DTStack/flinkx#127]
Hi, it seems that the jar is only available in your private repositories.

could you provide the jar ？com.ibm.db2:db2jcc:jar:3.72.44

we can not find the jar in https://mvnrepository.com/ and  https://maven.aliyun.com/mvn/search/.

this is the error log as below:
```
Failed to execute goal on project flinkx-db2-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-db2-core:jar:1.6: Failed to collect dependencies at com.ibm.db2:db2jcc:jar:3.72.44: Failed to read artifact descriptor for com.ibm.db2:db2jcc:jar:3.72.44: Could not transfer artifact com.ibm.db2:db2jcc:pom:3.72.44 from/to spring-snapshots (https://repo.spring.io/libs-snapshot-local): Failed to transfer file https://repo.spring.io/libs-snapshot-local/com/ibm/db2/db2jcc/3.72.44/db2jcc-3.72.44.pom with status code 409
```

the file path is as below:

https://github.com/DTStack/flinkx/blob/1.8.2/flinkx-db2/flinkx-db2-core/pom.xml

**Comment by kanata163** [comment]
https://github.com/DTStack/flinkx/tree/1.8.2/jars

**Comment by geekxingyun** [comment]
the issue have been resolved,thanks a lot.
