### ISSUE TITLE
emitWithMap 具体是处理什么场景数据源的 没看懂

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkx#129]

**Comment by lijiangbo** [comment]
hivewriter当前只针对来自binglog插件的map数据，会根据不同的mysql表写到不同的hive表里

**Comment by maidou75293** [comment]
mysql&nbsp; 好像也可以吧，我测试



---原始邮件---
发件人: "jiangbo"<notifications@github.com&gt;
发送时间: 2019年12月4日(星期三) 下午4:33
收件人: "DTStack/flinkx"<flinkx@noreply.github.com&gt;;
抄送: "maidou75293"<921635052@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [DTStack/flinkx] emitWithMap 具体是处理什么场景数据源的 没看懂 (#129)



hivewriter当前只针对来自binglog插件的map数据，会根据不同的mysql表写到不同的hive表里
