### ISSUE TITLE
编译失败 18.2 

### ISSUE THREAD

**Issue by emmataobao** [DTStack/flinkx#130]
pl.project13.maven:git-commit-id-plugin:2.2.6:revision (default) on project flinkx-core: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]

命令是官方命令

**Comment by emmataobao** [comment]
有没有好点的镜像源下载maven依赖推荐一下，不停的报错，好多依赖找不到。

**Comment by lijiangbo** [comment]
这个不是镜像源的问题，你可以把项目clone下来编译

**Comment by cailiming1994** [comment]
镜像源没有的依赖在flinkx工程根目录的jar文件夹内，自己手动添加到pom和仓库就行

**Comment by cailiming1994** [comment]
镜像源没有的依赖在flinkx工程根目录的jar文件夹内，自己手动添加到pom和仓库就行，还有就是克隆下来的工程没关系，但单独下载压缩包的工程要把pom中的maven git插件注释掉才能编译通过

**Comment by emmataobao** [comment]
好的谢谢，已经变异好了。正在测试es-to-mysql ，还在报错正在解决。有问题再咨询谢谢你们。

**Comment by cailiming1994** [comment]
不客气



发自我的iPhone6s


------------------ 原始邮件 ------------------
发件人: emmataobao <notifications@github.com&gt;
发送时间: 2019年12月11日 10:40
收件人: DTStack/flinkx <flinkx@noreply.github.com&gt;
抄送: cailiming1994 <824039685@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[DTStack/flinkx] 编译失败 18.2  (#130)




好的谢谢，已经变异好了。正在测试es-to-mysql ，还在报错正在解决。有问题再咨询谢谢你们。
