### ISSUE TITLE
提交到flink集群上的flinkx任务在数据同步完成之后会自动停掉，flinkx是否有配置或源码框架是否支持能让任务一直跑在flink集群上实时的同步数据呢？

### ISSUE THREAD

**Issue by cailiming1994** [DTStack/flinkx#134]

**Comment by kanata163** [comment]
flinkx里面的同步任务分为离线数据同步和实时数据同步，实时的目前只有binlog和kafka这两种reader插件，后续会增加SqlServer、postgresql和Oracle。
脚本参考example工程下对应脚本，说明文档可以看https://github.com/DTStack/flinkx/blob/1.8.2/docs/restore.md
