### ISSUE TITLE
mysql数据源采用mod并发拉取时并没有提速

### ISSUE THREAD

**Issue by pierre94** [DTStack/flinkx#143]
这边简单测了一下:

- DB环境: 腾讯云cdb 2核4GB内存 内核 MySQL5.6
- 表信息: id字段 int类型  PRIMARY KEY auto_increment 
- 数据量: 千万条、4GB

|模式 |并发 |耗时 |db 出流量峰值| 
|---|---|---|---|
|local |1 |3m 26s |25MB/s| 
|local |30 |4m 50s |13MB/s| 
|yarnPer |1 |2m 16s |39MB/s| 
|yarnPer |30 |5m 23s |13MB/s| 
|yarn |1 |2m 34s |30MB/s| 
|yarn |30 |4m 54 |14MB/s |

------
推测原因: 使用mod并发并不会利用到MySQL的索引，所以相当于全表扫描了30遍，MySQL层反而会更慢。

**Comment by kanata163** [comment]
你这里并发太多，数据库访问压力过大，建议通道数设置小点再测下。
通过explain SELECT COUNT(*) FROM kudu_data WHERE mod(id, 30) = 0;可以看到
type是index类型的，相当于按照索引的顺序的全表扫，相比于其他type确实是慢，不过多通道也没有其他更好的办法了。

**Comment by pierre94** [comment]
> 你这里并发太多，数据库访问压力过大，建议通道数设置小点再测下。
> 通过explain SELECT COUNT(*) FROM kudu_data WHERE mod(id, 30) = 0;可以看到
> type是index类型的，相当于按照索引的顺序的全表扫，相比于其他type确实是慢，不过多通道也没有其他更好的办法了。

writer单并发的处理能力比较慢，但增加Channel的话，就一起增加了。

**Comment by coolsummery** [comment]
> 你这里并发太多，数据库访问压力过大，建议通道数设置小点再测下。
> 通过explain SELECT COUNT(*) FROM kudu_data WHERE mod(id, 30) = 0;可以看到
> type是index类型的，相当于按照索引的顺序的全表扫，相比于其他type确实是慢，不过多通道也没有其他更好的办法了。

可以用explain SELECT * FROM kudu_data WHERE mod(id, 30) = 0;试试看，还走索引吗？
