### ISSUE TITLE
Mysql2Hive在Mode=overwrite的模式下设置Channel>=2的情况下，作业不成功

### ISSUE THREAD

**Issue by chungjunming** [DTStack/flinkx#144]
![image](https://user-images.githubusercontent.com/58799692/71227859-7b6c3680-231b-11ea-9bca-57bd9f6d5bd8.png)
生成两个隐藏文件，执行不成功。
而在Mode=Append模式，Channel>=2时无此问题。
但在Channel设置为1时，Mode=overwrite无此问题。
请问这是什么原因？

**Comment by kanata163** [comment]
用的哪个分支，脚本贴一下。执行不成功，有报错吗？

**Comment by chungjunming** [comment]
> 用的哪个分支，脚本贴一下。执行不成功，有报错吗？
用的1.8.1分支。
![image](https://user-images.githubusercontent.com/58799692/71238361-d7948200-233e-11ea-9b1d-1579d0e11224.png)
![image](https://user-images.githubusercontent.com/58799692/71238391-e844f800-233e-11ea-908a-9921b2a9ac50.png)
生成3个task。
第一个task报错信息如下：
![image](https://user-images.githubusercontent.com/58799692/71238486-24785880-233f-11ea-9583-6b35e653edd7.png)
第二个task：
![image](https://user-images.githubusercontent.com/58799692/71238544-4c67bc00-233f-11ea-81fd-674e0bd3038e.png)
第三个task：
![image](https://user-images.githubusercontent.com/58799692/71238560-60abb900-233f-11ea-8255-d0e0de3e3e14.png)

**Comment by kanata163** [comment]
我用1.8.1分支跑了几次Mode=overwrite，Channel=3的都成功了，没出现你这样的问题。
这个错是在`HdfsOutputFormat.waitForAllTasksToFinish()`里面定义的，目的是只有当多个通道的全都正常写完了，才认为任务是执行成功了。每个通道执行结束时会创建`finished tag`，
你可以在日志里面检查下这个是否都成功创建了。

> Channel:[0], currentBlockFileNamePrefix:[0.53d824d0225ae4a1f3f78b238bc970d5], tmpPath:[hdfs://ns1/user/hive/warehouse/tudou.db/kudu_data_txt/pt=20191226/.data], finishedPath:[hdfs://ns1/user/hive/warehouse/tudou.db/kudu_data_txt/pt=20191226/.finished/0]

> Create finished tag dir:hdfs://ns1/user/hive/warehouse/tudou.db/kudu_data_txt/pt=20191226/.finished/0
