### ISSUE TITLE
异构数据源reader和writer设置不同的Parallelism数

### ISSUE THREAD

**Issue by pierre94** [DTStack/flinkx#145]
#143 
这个issue想到的场景。
- 读1个Parallelism可能已经很快，多个Parallelism可能反而慢了
- 写需要多个Parallelism

**Comment by lijiangbo** [comment]
这个功能会在近期支持的

**Comment by pierre94** [comment]
![image](https://user-images.githubusercontent.com/12579749/77060008-d98be100-6a12-11ea-97c1-9b00c457954f.png)
官方已支持
