### ISSUE TITLE
mysql to hive如何overwrite，看代码是删除整个表再插入的，这样逻辑不对吧，不是删除旧分区吗

### ISSUE THREAD

**Issue by mingge12321** [DTStack/flinkx#146]
![aa](https://user-images.githubusercontent.com/31925675/71254679-b9427c80-2366-11ea-9667-c0e74804297f.png)

**Comment by mingge12321** [comment]
@kanata163 帮忙看下，谢谢

**Comment by lijiangbo** [comment]
这块逻辑确实是有问题的，我们会尽快修复的

**Comment by lijiangbo** [comment]
已经修复
