### ISSUE TITLE
flink on yarn获取jobid

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/flinkx#148]
2.1 通过Flink REST接口获取
任务运行期间，可以通过Flink REST接口获取Accumulator数据，名称和上面给出的一致。

api：http://host:8088/proxy/application_1569335225689_4172//jobs/d5582272d29ff38e10416a4043a86cad/accumulators

d5582272d29ff38e10416a4043a86cad这个id怎么获取?

**Comment by kanata163** [comment]
`RichInputFormat.initJobInfo()`里面可以拿到
