### ISSUE TITLE
standalone提交任务运行报错Failed to retrieve JobManager address，local提交正常跑

### ISSUE THREAD

**Issue by zhouyunlong** [DTStack/flinkx#15]
flink集群跑自带的测试样例能正常跑通。

命令：bin/flinkx -mode standalone -job /tmp/zyl/flink-data-transfer/jobs/mysql_to_mysql.json -plugin /tmp/zyl/flink-data-transfer/plugins -flinkconf /opt/flink-1.6.1/conf

standalone提交任务运行报错：
14:08:18.828 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/tmp/zyl/flink-data-transfer
14:08:18.829 [main] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=bd129106:2181,bd129107:2181,bd129108:2181 sessionTimeout=60000 watcher=org.apache.flink.shaded.curator.org.apache.curator.ConnectionState@4c60d6e9
14:08:18.831 [main] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - zookeeper.disableAutoWatchReset is false
14:08:18.843 [main-SendThread(bd129108:2181)] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Opening socket connection to server bd129108/192.168.129.108:2181. Will not attempt to authenticate using SASL (unknown error)
14:08:18.844 [main-SendThread(bd129108:2181)] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Socket connection established to bd129108/192.168.129.108:2181, initiating session
14:08:18.847 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Session establishment request sent on bd129108/192.168.129.108:2181
14:08:18.883 [main-SendThread(bd129108:2181)] INFO org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Session establishment complete on server bd129108/192.168.129.108:2181, sessionid = 0x166282611458a6b, negotiated timeout = 60000
14:08:18.894 [main-EventThread] INFO org.apache.flink.shaded.curator.org.apache.curator.framework.state.ConnectionStateManager - State change: CONNECTED
14:08:19.077 [main] INFO org.apache.flink.runtime.leaderretrieval.ZooKeeperLeaderRetrievalService - Starting ZooKeeperLeaderRetrievalService.
14:08:19.103 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166282611458a6b, packet:: clientPath:null serverPath:null finished:false header:: 1,3  replyHeader:: 1,691490210287,0  request:: '/flinkx,F  response:: s{691489993987,691489993987,1539159387219,1539159387219,0,1,0,0,0,1,691489993988} 
14:08:19.105 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166282611458a6b, packet:: clientPath:null serverPath:null finished:false header:: 2,3  replyHeader:: 2,691490210287,0  request:: '/flinkx/default,F  response:: s{691489993988,691489993988,1539159387246,1539159387246,0,8,0,0,0,4,691490163480} 
14:08:19.112 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166282611458a6b, packet:: clientPath:null serverPath:null finished:false header:: 3,3  replyHeader:: 3,691490210287,0  request:: '/flinkx,F  response:: s{691489993987,691489993987,1539159387219,1539159387219,0,1,0,0,0,1,691489993988} 
14:08:19.114 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166282611458a6b, packet:: clientPath:null serverPath:null finished:false header:: 4,3  replyHeader:: 4,691490210287,0  request:: '/flinkx/default,F  response:: s{691489993988,691489993988,1539159387246,1539159387246,0,8,0,0,0,4,691490163480} 
14:08:19.116 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166282611458a6b, packet:: clientPath:null serverPath:null finished:false header:: 5,3  replyHeader:: 5,691490210287,0  request:: '/flinkx/default/leader,F  response:: s{691489993989,691489993989,1539159387272,1539159387272,0,81012,0,0,0,4,691490163489} 
14:08:19.118 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166282611458a6b, packet:: clientPath:null serverPath:null finished:false header:: 6,3  replyHeader:: 6,691490210287,0  request:: '/flinkx/default/leader/00000000000000000000000000000000,F  response:: s{691490098615,691490098615,1539421562506,1539421562506,0,0,0,0,0,0,691490098615} 
14:08:19.120 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Reading reply sessionid:0x166282611458a6b, packet:: clientPath:/flinkx/default/leader/00000000000000000000000000000000/job_manager_lock serverPath:/flinkx/default/leader/00000000000000000000000000000000/job_manager_lock finished:false header:: 7,3  replyHeader:: 7,691490210287,-101  request:: '/flinkx/default/leader/00000000000000000000000000000000/job_manager_lock,T  response::  
14:08:39.140 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166282611458a6b after 0ms
14:08:59.158 [main-SendThread(bd129108:2181)] DEBUG org.apache.flink.shaded.zookeeper.org.apache.zookeeper.ClientCnxn - Got ping response for sessionid: 0x166282611458a6b after 0ms
14:09:19.121 [main] INFO org.apache.flink.runtime.leaderretrieval.ZooKeeperLeaderRetrievalService - Stopping ZooKeeperLeaderRetrievalService.
Exception in thread "main" java.lang.RuntimeException: Failed to retrieve JobManager address
        at org.apache.flink.client.program.ClusterClient.getJobManagerAddress(ClusterClient.java:308)
        at org.apache.flink.client.program.StandaloneClusterClient.getWebInterfaceURL(StandaloneClusterClient.java:56)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:92)
Caused by: org.apache.flink.runtime.leaderretrieval.LeaderRetrievalException: Could not retrieve the leader address and leader session ID.
        at org.apache.flink.runtime.util.LeaderRetrievalUtils.retrieveLeaderConnectionInfo(LeaderRetrievalUtils.java:113)
        at org.apache.flink.client.program.ClusterClient.getJobManagerAddress(ClusterClient.java:302)
        ... 2 more
Caused by: java.util.concurrent.TimeoutException: Futures timed out after [60000 milliseconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
        at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:190)
        at scala.concurrent.Await.result(package.scala)
        at org.apache.flink.runtime.util.LeaderRetrievalUtils.retrieveLeaderConnectionInfo(LeaderRetrievalUtils.java:111)
        ... 3 more

哪位帮忙看下，谢谢

**Comment by yangsishu** [comment]
现在支持flink1.4和flink1.5，master是flink1.4编译的

**Comment by zhouyunlong** [comment]
> 现在支持flink1.4和flink1.5，master是flink1.4编译的

第一个问题：
StreamSource<OUT, ?> sourceOperator;
        if (function instanceof StoppableFunction) {
            sourceOperator = new StoppableStreamSource<>(cast2StoppableSourceFunction(function));
        } else {
            sourceOperator = new StreamSource<>(function);
        }

        return new DataStreamSource<>(this, typeInfo, sourceOperator, isParallel, sourceName);
    }

源码下载下来：
sourceOperator = new StoppableStreamSource<>(cast2StoppableSourceFunction(function));
这行会有报错？



第二个问题：flink是1.5，standalone模式，没有使用HA，flinkx也是下载flinkx-r1.5.0版本的，执行命令：
[root@bd129106 flink-data-transfer]# bin/flinkx -mode standalone -job /tmp/zyl/flink-data-transfer/jobs/mysql_to_mysql.json -plugin /tmp/zyl/flink-data-transfer/plugins -flinkconf /tmp/zyl/flink-data-transfer/flinkconf/

会报如下错误：
16:59:53.539 [main] DEBUG org.apache.flink.shaded.netty4.io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
16:59:53.550 [main] DEBUG org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
16:59:53.550 [main] DEBUG org.apache.flink.shaded.netty4.io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
16:59:53.559 [main] INFO org.apache.flink.runtime.rest.RestClient - Rest client endpoint started.
Exception in thread "main" org.apache.flink.client.deployment.ClusterRetrieveException: Couldn't retrieve standalone cluster
        at org.apache.flink.client.deployment.StandaloneClusterDescriptor.retrieve(StandaloneClusterDescriptor.java:51)
        at com.dtstack.flinkx.launcher.ClusterClientFactory.createStandaloneClient(ClusterClientFactory.java:66)
        at com.dtstack.flinkx.launcher.ClusterClientFactory.createClusterClient(ClusterClientFactory.java:55)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:87)
Caused by: java.lang.NullPointerException
        at org.apache.flink.util.Preconditions.checkNotNull(Preconditions.java:58)
        at org.apache.flink.client.program.rest.RestClusterClient.<init>(RestClusterClient.java:194)
        at org.apache.flink.client.program.rest.RestClusterClient.<init>(RestClusterClient.java:157)
        at org.apache.flink.client.deployment.StandaloneClusterDescriptor.retrieve(StandaloneClusterDescriptor.java:49)
        ... 3 more

**Comment by yangsishu** [comment]
拉下1.5 分支，第二个问题改了，你再试下

**Comment by yangsishu** [comment]
你先用yarn模式，yarn模式是没问题的

**Comment by Liguangmin** [comment]
我之前也遇到同样的问题，V1.4版本，FLink集群按照HA方式部署后就执行成功了

**Comment by zhouyunlong** [comment]
> 我之前也遇到同样的问题，V1.4版本，FLink集群按照HA方式部署后就执行成功了

你源码下载的V1.4版本，flink集群版本也是1.4，standlone 的HA方式部署的，能成功？
