### ISSUE TITLE
updateKey格式问题

### ISSUE THREAD

**Issue by shenlanqianlan1102** [DTStack/flinkx#155]
可以描述清楚updateKey的格式 这里是一个Map<String,List<String>>对应json里面键值对中 key是可以随意定义的 只有value需要填写唯一索引的一个数组 这里感觉传入的json可以简化 然后后面转换为
Map<String,List<String>>

**Comment by lijiangbo** [comment]
确实是这样的，这个问题我们会加入优化列表的
