### ISSUE TITLE
关于flinkx binlog插件的问题

### ISSUE THREAD

**Issue by cailiming1994** [DTStack/flinkx#158]
阿里canal自身支持增量采集binlog数据到其他系统的，请问flinkx的binlog插件是解决了canal的哪些问题和局限？

**Comment by lijiangbo** [comment]
FlinkX用的就是canal，只是做了集成，目前没有其它改动

**Comment by mgr1979** [comment]
canal在读取binlog的时候报：“Received error packet: errno = 1236, sqlstate = HY000 errmsg = Could not find first log file name in binary log index file”,如果是canal，可以删除meta.dat文件，再重新启动。不知道集成的canal怎么重启。
