### ISSUE TITLE
关于flinkx binlog插件实时增量同步数据到关系型数据库问题

### ISSUE THREAD

**Issue by cailiming1994** [DTStack/flinkx#159]
配置使用flinkx的binlog读插件和关系型数据库写插件，Flinkx支持将binlog数据增量实时同步到关系型数据库吗？还是只支持将binlog数据实时增量写到HDFS或kafka，不支持写到关系型数据库

**Comment by lijiangbo** [comment]
可以写到关系数据库，但是目前会把一条binlog日志写入一个字段里
