### ISSUE TITLE
k8s 容器化调度支持么

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkx#162]

**Comment by lijiangbo** [comment]
flinkx本质上就是一个flink程序，flink是支持Kubernetes部署的，但是目前flinkx本身的启动模式不支持Kubernetes

**Comment by shierad123** [comment]
> flinkx本质上就是一个flink程序，flink是支持Kubernetes部署的，但是目前flinkx本身的启动模式不支持Kubernetes

那可以在k8s的flink集群上运行flinkx吗?

**Comment by shierad123** [comment]
> flinkx本质上就是一个flink程序，flink是支持Kubernetes部署的，但是目前flinkx本身的启动模式不支持Kubernetes

那可以在k8s的flink集群上运行flinkx吗?

**Comment by cjjxfli** [comment]
可以。挂载NFS作为持久化存储即可

**Comment by deadwind4** [comment]
现已支持

**Comment by geosmart** [comment]
related commit 
https://github.com/DTStack/flinkx/commit/b37ffa8736fb37920da4532a65f94c44d6542de2
