### ISSUE TITLE
Flinkx on yarn 报错

### ISSUE THREAD

**Issue by ASiegeLion** [DTStack/flinkx#163]
编译了Flinkx 成功，运行Flinkx on yarn 时日志报错
![image](https://user-images.githubusercontent.com/30170267/74336462-4212ed00-4dd9-11ea-8874-e39f83681e78.png)
查看lib下的jar包里面确实没有yarn这个类，这是编译失败了吗，还是要把hadoop的jar加入到classpath 中

**Comment by ASiegeLion** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/yarn/conf/YarnConfiguration
	at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:101)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.yarn.conf.YarnConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by ASiegeLion** [comment]
上面这个是图片上的异常

**Comment by pierre94** [comment]
> 查看lib下的jar包里面确实没有yarn这个类，这是编译失败了吗，还是要把hadoop的jar加入到classpath 中

正常的flink on yarn任务可以正常运行么？ 还有你的flink版本是？

**Comment by lijiangbo** [comment]
这个问题我们会尽快修复的

**Comment by ASiegeLion** [comment]
flink on yarn 任务能正常运行，flink 版本是1.7.2 ， flinkx 需要依赖flink 么？ 没有独自构建所有的jar包吗

**Comment by ASiegeLion** [comment]
> > 查看lib下的jar包里面确实没有yarn这个类，这是编译失败了吗，还是要把hadoop的jar加入到classpath 中
> 
> 正常的flink on yarn任务可以正常运行么？ 还有你的flink版本是？

flink on yarn 任务能正常运行，flink 版本是1.7.2 ， flinkx 需要依赖flink 么？ 没有独自构建所有的jar包吗

**Comment by ASiegeLion** [comment]
> 这个问题我们会尽快修复的

这是啥问题，缺少依赖？

**Comment by ASiegeLion** [comment]
> 缺少hadoop的依赖

我尝试在把hadoop的jar 包放在flinkx 的lib 下面，但是好像还是不行，

**Comment by lijiangbo** [comment]
要放到flink的lib下面

**Comment by ASiegeLion** [comment]
> 要放到flink的lib下面

我试一下，flinkx 依赖于flink的环境？所以要配置flink home?

**Comment by lijiangbo** [comment]
local模式不需要flink环境，其它模式需要flink环境

**Comment by ASiegeLion** [comment]
> local模式不需要flink环境，其它模式需要flink环境

我已经把hadoop yarn jar 包放到flink 的 lib 下 ，并且配置了flink_home ，还是同样的错误

![火星图片_20200217_151441](https://user-images.githubusercontent.com/30170267/74631615-5d467980-5198-11ea-8781-6c99a4d8f147.jpg)
![火星图片_20200217_151459](https://user-images.githubusercontent.com/30170267/74631616-5ddf1000-5198-11ea-8731-fa95cfdc91c6.jpg)

**Comment by tb77506668** [comment]
这个问题解决了吗,我也是遇到一模一样的问题

**Comment by oceanos** [comment]
我的经验是把命令行参数改成 -flinkLibJar /opt/flink-1.8.1/lib，也就是说这里要配成flink-1.8.1的lib目录，而且要把flinkx的plugins都copy到flink的lib里，yarn相关的也copy进去
![image](https://user-images.githubusercontent.com/11856424/78854937-2cc2e380-7a55-11ea-9e70-0838495e97ee.png)

**Comment by kanata163** [comment]
需要添加flink-shaded-hadoop2-uber包，下载地址：https://repo.maven.apache.org/maven2/org/apache/flink/flink-shaded-hadoop-2-uber/
