### ISSUE TITLE
开启flinkx时报异常

### ISSUE THREAD

**Issue by jehliow** [DTStack/flinkx#167]
我在本地模式进行了测试
bin/flinkx -mode local -job /lzh/software/flinkx/jobs/MyOracle.json -pluginRoot /lzh/software/flinkx/plugins -confProp '{"flink.checkpoint.interval":60000,"flink.checkpoint.stateBackend":"/tmp/checkpoint_dir"}' -s /tmp/checkpoint_dir/0481473685a8e7d22e7bd079d6e5c08c/chk-*

但是出现了下面的异常

09:39:14.913 [main] INFO com.dtstack.flinkx.Main - Open checkpoint with interval:60000
09:39:15.005 [main] INFO com.dtstack.flinkx.classloader.ClassLoaderManager - jarUrl:file:/lzh/software/flinkx/plugins/common/flinkx-rdb-core-1.8.4_rc0.jar_file:/lzh/software/flinkx/plugins/common/flinkx-rdb-reader-1.8.4_rc0.jar_file:/lzh/software/flinkx/plugins/common/flinkx-rdb-writer-1.8.4_rc0.jar_file:/lzh/software/flinkx/plugins/oraclereader/flinkx-oracle-reader-1.8.4_rc0.jar create ClassLoad successful...
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.dtstack.flinkx.reader.DataReaderFactory.getDataReader(DataReaderFactory.java:52)
        at com.dtstack.flinkx.Main.main(Main.java:97)
        at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:93)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.dtstack.flinkx.reader.DataReaderFactory.lambda$getDataReader$0(DataReaderFactory.java:49)
        at com.dtstack.flinkx.classloader.ClassLoaderSupplierCallBack.callbackAndReset(ClassLoaderSupplierCallBack.java:33)
        at com.dtstack.flinkx.classloader.ClassLoaderManager.newInstance(ClassLoaderManager.java:43)
        at com.dtstack.flinkx.reader.DataReaderFactory.getDataReader(DataReaderFactory.java:46)
        ... 2 more
Caused by: java.lang.NullPointerException
        at com.dtstack.flinkx.rdb.datareader.JdbcDataReader.<init>(JdbcDataReader.java:90)
        at com.dtstack.flinkx.oracle.reader.OracleReader.<init>(OracleReader.java:37)
        ... 10 more

**Comment by jehliow** [comment]
json文件配置在reader那里写错了

**Comment by lijiangbo** [comment]
麻烦把json发一下

**Comment by jehliow** [comment]
您好！我修改好了。就是一些小错误。但是有新问题。开启的时候。
14:32:26.596 [flink-akka.actor.default-dispatcher-2] INFO org.apache.flink.runtime.rpc.akka.AkkaRpcService - Stopped Akka RPC service.
347 Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Could not retrieve JobResult.
348     at org.apache.flink.runtime.minicluster.MiniCluster.executeJobBlocking(MiniCluster.java:634)
349     at com.dtstack.flink.api.java.MyLocalStreamEnvironment.execute(MyLocalStreamEnvironment.java:152)
350     at com.dtstack.flinkx.Main.main(Main.java:116)
351     at com.dtstack.flinkx.launcher.Launcher.main(Launcher.java:93)
352 Caused by: org.apache.flink.runtime.client.JobSubmissionException: Failed to submit job.
353     at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$internalSubmitJob$2(Dispatcher.java:309)
354     at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
355     at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
356     at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
357     at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
358     at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
359     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
360     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
361     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
362     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
363 Caused by: java.lang.RuntimeException: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
364     at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:36)
365     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
366     ... 6 more
367 Caused by: org.apache.flink.runtime.client.JobExecutionException: Could not set up JobManager
368     at org.apache.flink.runtime.jobmaster.JobManagerRunner.<init>(JobManagerRunner.java:152)
369     at org.apache.flink.runtime.dispatcher.DefaultJobManagerRunnerFactory.createJobManagerRunner(DefaultJobManagerRunnerFactory.java:76)
370     at org.apache.flink.runtime.dispatcher.Dispatcher.lambda$createJobManagerRunner$5(Dispatcher.java:351)
371     at org.apache.flink.util.function.CheckedSupplier.lambda$unchecked$0(CheckedSupplier.java:34)
372     ... 7 more
373 Caused by: java.io.FileNotFoundException: Cannot find checkpoint or savepoint file/directory '/tmp/checkpoint_dir/0481473685a8e7d22e7bd079d6e5c08c/chk-*' on file syst    em 'file'.
374     at org.apache.flink.runtime.state.filesystem.AbstractFsCheckpointStorage.resolveCheckpointPointer(AbstractFsCheckpointStorage.java:241)
375     at org.apache.flink.runtime.state.filesystem.AbstractFsCheckpointStorage.resolveCheckpoint(AbstractFsCheckpointStorage.java:109)
376     at org.apache.flink.runtime.checkpoint.CheckpointCoordinator.restoreSavepoint(CheckpointCoordinator.java:1100)
377     at org.apache.flink.runtime.jobmaster.JobMaster.tryRestoreExecutionGraphFromSavepoint(JobMaster.java:1266)
378     at org.apache.flink.runtime.jobmaster.JobMaster.createAndRestoreExecutionGraph(JobMaster.java:1190)
379     at org.apache.flink.runtime.jobmaster.JobMaster.<init>(JobMaster.java:287)
380     at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:83)
381     at org.apache.flink.runtime.jobmaster.factories.DefaultJobMasterServiceFactory.createJobMasterService(DefaultJobMasterServiceFactory.java:37)
382     at org.apache.flink.runtime.jobmaster.JobManagerRunner.<init>(JobManagerRunner.java:146)
383     ... 10 more

**Comment by lijiangbo** [comment]
-s /tmp/checkpoint_dir/0481473685a8e7d22e7bd079d6e5c08c/chk-* 是指定任务恢复的checkpoint文件，如果是第一次运行，不要指定这个参数，如果开启了断点续传功能或者使用实时采集功能时会产生快照文件，如果任务运行中失败，可以使用这个参数使任务从失败的位置继续运行

**Comment by jehliow** [comment]
好的，感谢。
但是我集群的的flink是1.7.0的，hadoop是Hadoop 2.6.0-cdh5.7.0版本。请问打包到开启需要注意什么吗？影响大不大？

**Comment by lijiangbo** [comment]
那需要使用flink1.7重新编译了，可能需要改一些启动类里的参数。运行的的话要看具体的运行模式：
如果启动session时有-ship参数指定插件路径，那么不需要在计算节点放插件，如果没有-sjip参数，那么需要在每个计算节点固定的目录下插件包

**Comment by jehliow** [comment]
那么最好用flink1.8.2以上的版本最好对吗？

**Comment by lijiangbo** [comment]
这个不一定，Flink不同版本功能上可能有差距，但是FlinkX目前没有依赖Flink某个版本的特定功能，所以flink具体用哪个版本还要看对flink有没有其它需求

**Comment by jehliow** [comment]
那我git编译flinkx之前很多版本依赖都需要修改了？

**Comment by lijiangbo** [comment]
只需要修改flink版本就行
