### ISSUE TITLE
flink1.10支持么

### ISSUE THREAD

**Issue by amoygao** [DTStack/flinkx#170]

**Comment by lijiangbo** [comment]
目前正在开发支持，预计3月底可用

**Comment by czy006** [comment]
如果想参与开发组件 如何参与 ？ 我没看到1.10的分支情况

**Comment by lijiangbo** [comment]
flink 1.10的升级目前我们已经在开发中了，参与其它插件开发的化按照一般的流程就行：
1.fork仓库到自己的账号下；
2.开发插件，测试；
3.提交Pull Request给我们；
4.我们审核后合并到主分支上；

**Comment by kanata163** [comment]
@amoygao @czy006 已支持1.10
