### ISSUE TITLE
compile error :can't find org.apache.commons.net.telnet.TelnetClient

### ISSUE THREAD

**Issue by oceanos** [DTStack/flinkx#173]

**Comment by lijiangbo** [comment]
请问你用哪个分支编译的

**Comment by oceanos** [comment]
> 请问你用哪个分支编译的
1.8_release

**Comment by lijiangbo** [comment]
请检查下本地maven仓库里有没有包：commons-net-3.1.jar

**Comment by oceanos** [comment]
> 请检查下本地maven仓库里有没有包：commons-net-3.1.jar

本地仓库里是有的，SFTPHandler 这个类也遇到类似的问题，解决办法是在flinkx-core的pom.xml里添加相关依赖
`<dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
            <version>3.6</version>
        </dependency>
        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch</artifactId>
            <version>0.1.51</version>
        </dependency>`
