### ISSUE TITLE
可以通过接口方式调用执行吗？

### ISSUE THREAD

**Issue by RunningXuan** [DTStack/flinkx#175]
可以通过接口方式调用执行吗？就是通过web页面设计好json，然后调用flinkx的接口执行任务！

**Comment by lijiangbo** [comment]
目前不支持

**Comment by RunningXuan** [comment]
![image](https://user-images.githubusercontent.com/47099551/76673724-c035ff80-65e2-11ea-983f-7f353321ab1a.png)
这个在哪里可以体验到？目前有计划支持接口吗？

**Comment by lijiangbo** [comment]
我们有一套完整的大数据平台，支持界面配置任务，调度任务，任务运维，但是是收费的，开源出来的flinkx目前没有web界面，近期会考虑增加简单的接口的。

**Comment by AriesMg** [comment]
> 目前不支持

大概什么时候能支持呢?

**Comment by deadwind4** [comment]
商业版支持，开源目前还没有
