### ISSUE TITLE
支持apache pulsar的融合

### ISSUE THREAD

**Issue by cmdares** [DTStack/flinkx#183]
1、近年来Pulsar日臻完善，从技术、架构、性能等综合方面大有取代kafka之势
2、大型互联网厂商已经大规模采用Pulsar作为基建
希望官方仔细评估pulsar的技术和架构，将产品能力针对Pulsar做一定的兼容和优化，包括性能和易用性

**Comment by yangsishu** [comment]
flinkx已经支持Pulsar了

**Comment by cmdares** [comment]
其实想把问题发到flinkStreamSQL中来提问，结果发到这里了。
@yangsishu 您看下flinkStreamSQL 有这方面打算吗，目前Flink和Pulsar正在融合适配

**Comment by pierre94** [comment]
> 其实想把问题发到flinkStreamSQL中来提问，结果发到这里了。
> @yangsishu 您看下flinkStreamSQL 有这方面打算吗，目前Flink和Pulsar正在融合适配

pulsar PMC 开发的 https://github.com/streamnative/pulsar-flink
