### ISSUE TITLE
支持rest方式提交任务

### ISSUE THREAD

**Issue by cmdares** [DTStack/flinkx#184]
可否发布服务，将一些常用动作服务化，变于系统集成。
感谢！

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lijiangbo** [comment]
正在开发中

**Comment by RunningXuan** [comment]
支持rest方式提交任务预计到什么时间能用？很期待这个！

**Comment by deadwind4** [comment]
商业版有，开源暂不支持
