### ISSUE TITLE
HdfsWriter

### ISSUE THREAD

**Issue by Mr-Malone** [DTStack/flinkx#19]
你好，想请教下为什么hdfswriter写数据要通过hive，而不是直接写的hdfs文件呢？

**Comment by yangsishu** [comment]
就是直接写hdfs的

**Comment by yangsishu** [comment]
你看的是那个分支的代码

**Comment by Mr-Malone** [comment]
那为何要字段映射？

**Comment by Mr-Malone** [comment]
看的是现在最新的版本，hdfswriter 里的columns 参数是必选的。

**Comment by lijiangbo** [comment]
> 
> 
> 看的是现在最新的版本，hdfswriter 里的columns 参数是必选的。

hdfs里的文件有orc,parquet等格式，这文件里是包含元数据信息的，必须填写字段名称或者字段索引

**Comment by Mr-Malone** [comment]
原来是这样，谢谢大佬

**Comment by Mr-Malone** [comment]
写text文件是否可以不指定字段映射？

**Comment by lijiangbo** [comment]
> 
> 
> 写text文件是否可以不指定字段映射？

需要指定的，虽然是写字符串，但是我们也会对写入的数据先做类型处理，比如时间类型的数据，会指定特定格式写入的
