### ISSUE TITLE
Yarn per job state backend (confProp) 配置没生效

### ISSUE THREAD

**Issue by oceanos** [DTStack/flinkx#196]
命令行：
./flinkx -mode yarnPer \
-job /opt/flinkx-1.8.5/example/mysql_to_hive.json \
-pluginRoot /opt/flinkx-1.8.5/plugins/ \
-flinkconf /opt/flink-1.8.1/conf/ \
-yarnconf /opt/flinkx-1.8.5/conf/ \
-flinkLibJar /opt/flink-1.8.1/lib \
-confProp "{\"flink.checkpoint.interval\":30000,\"flink.checkpoint.stateBackend\":\"hdfs://myHAservice/user/admin/flinkx/checkpoints\",\"jobmanager.memory.mb\":2048,\"taskmanager.memory.mb\":2048}" \
-queue root.admin \
-pluginLoadMode classpath \
-jobid myJob

nohup.out日志：(内存设置也没生效)
14:49:58.315 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.rpc.address, localhost
14:49:58.316 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.rpc.port, 6123
14:49:58.316 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: jobmanager.heap.size, 2048m
14:49:58.316 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.heap.size, 2048m
14:49:58.316 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: taskmanager.numberOfTaskSlots, 1
14:49:58.316 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: parallelism.default, 1
14:49:58.317 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: state.backend, filesystem
14:49:58.317 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: state.checkpoints.dir, hdfs://myHAservice/user/admin/flinkx/checkpoints
14:49:58.317 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: state.savepoints.dir, hdfs://myHAservice/user/admin/flinkx/savepoints
14:49:58.318 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: security.kerberos.login.use-ticket-cache, true
14:49:58.318 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: security.kerberos.login.keytab, /opt/keytab/admin.keytab
14:49:58.318 [main] INFO org.apache.flink.configuration.GlobalConfiguration - Loading configuration property: security.kerberos.login.principal, admin
14:49:58.325 [main] INFO com.dtstack.flinkx.launcher.perjob.PerJobSubmitter - conProp:{flink.checkpoint.interval=30000, taskmanager.memory.mb=2048, flink.checkpoint.stateBackend=hdfs://myHAservice/user/admin/flinkx/checkpoints, jobmanager.memory.mb=2048}
14:49:59.072 [main] INFO com.dtstack.flinkx.launcher.perjob.PerJobClusterClientBuilder - ----init yarn success ----
**14:49:59.875 [main] WARN org.apache.flink.yarn.AbstractYarnClusterDescriptor - The JobManager or TaskManager memory is below the smallest possible YARN Container size. The value of 'yarn.scheduler.minimum-allocation-mb' is '1024'. Please increase the memory size.YARN will allocate the smaller containers but the scheduler will account for the minimum-allocation-mb, maybe not all instances you requested will start.
14:49:59.875 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Cluster specification: ClusterSpecification{masterMemoryMB=1024, taskManagerMemoryMB=1024, numberTaskManagers=1, slotsPerTaskManager=1, priority=0}**
14:50:00.187 [main] WARN org.apache.flink.yarn.AbstractYarnClusterDescriptor - The configuration directory ('/opt/flink-1.8.1/conf/') contains both LOG4J and Logback configuration files. Please delete or rename one of them.
14:50:07.017 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Adding delegation token to the AM container..
14:50:07.124 [main] INFO org.apache.flink.yarn.Utils - Attempting to obtain Kerberos security token for HBase
14:50:07.125 [main] INFO org.apache.flink.yarn.Utils - HBase is not available (not packaged with this application): ClassNotFoundException : "org.apache.hadoop.hbase.HBaseConfiguration".
14:50:07.131 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Submitting application master application_1581335885532_11687
14:50:07.361 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Waiting for the cluster to be allocated
14:50:07.362 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - Deploying cluster, current state ACCEPTED
14:50:16.301 [main] INFO org.apache.flink.yarn.AbstractYarnClusterDescriptor - YARN application has been deployed successfully.
14:50:16.688 [main] INFO org.apache.flink.runtime.rest.RestClient - Rest client endpoint started.
14:50:16.690 [main] INFO com.dtstack.flinkx.launcher.perjob.PerJobSubmitter - deploy per_job with appId: application_1581335885532_11687

yarn 日志：
2020-04-16 14:50:15,726 INFO  org.apache.flink.runtime.jobmaster.JobMaster                  - Using restart strategy NoRestartStrategy for Flink Job (d82072e01a996d64fd8fb64b9ed7d5a4).
2020-04-16 14:50:15,749 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph        - Job recovers via failover strategy: full graph restart
2020-04-16 14:50:15,955 INFO  org.apache.flink.runtime.jobmaster.JobMaster                  - Running initialization on master for job Flink Job (d82072e01a996d64fd8fb64b9ed7d5a4).
2020-04-16 14:50:16,075 INFO  org.apache.flink.runtime.jobmaster.JobMaster                  - Successfully ran initialization on master in 119 ms.
2020-04-16 14:50:16,103 INFO  org.apache.flink.runtime.jobmaster.JobMaster                  - **No state backend has been configured**, using default (Memory / JobManager) MemoryStateBackend (data in heap memory / checkpoints to JobManager) (checkpoints: 'null', savepoints: 'null', asynchronous: TRUE, maxStateSize: 5242880)

**Comment by kanata163** [comment]
@oceanos 
bug已修复
