### ISSUE TITLE
请问同样用于离线数据同步flinkx和datax主要区别在什么地方

### ISSUE THREAD

**Issue by Zuckonit** [DTStack/flinkx#21]

**Comment by yangsishu** [comment]
开源的datax是单机的，也没有界面看任务的运行的状态

**Comment by yangsishu** [comment]
flinkx的介绍

https://yq.aliyun.com/articles/604433?spm=a2c4e.11155435.0.0.50373312xRMvVT

**Comment by yuhai1023** [comment]
感觉这东西就是在datax配置的基础上，为了兼容就的同步任务而产生的东西。并没有改变离线的方式
