### ISSUE TITLE
hdfswriter

### ISSUE THREAD

**Issue by Mr-Malone** [DTStack/flinkx#22]
hdfswriter能否指定文件名写入,现在的参数filename不能实现这个作用,

**Comment by Mr-Malone** [comment]
![image](https://user-images.githubusercontent.com/39895740/49803455-d96e5180-fd8a-11e8-9a25-30e395fc7539.png)

**Comment by demotto** [comment]
因为hdfs支持并发追加到同一个文件， 所以如果支持直接向文件写入而不是向目录写入的话，就没法支持多通道写入了。  而且对于hive表来说，底层的数据文件都是存到一个hdfs文件夹下面的.
