### ISSUE TITLE
windows系统下提交任务,执行任务在perjob模式(部署在linux系统), 提示找不到入口类?  linux下提交可以成功执行

### ISSUE THREAD

**Issue by fanliunian** [DTStack/flinkx#221]
![图片](https://user-images.githubusercontent.com/20262192/83004241-ff041f00-a041-11ea-8634-ff781d7c7658.png)

**Comment by kanata163** [comment]
不支持从Windows环境提交任务

**Comment by lvyanquan** [comment]
这个是classpath分隔符不同导致的问题，将org.apache.flink.yarn.YarnClusterDescriptor里的
File.pathSeparator 改为 ApplicationConstants.CLASS_PATH_SEPARATOR 就可以了
