### ISSUE TITLE
oraclereader to oraclewriter 断点续传问题

### ISSUE THREAD

**Issue by hzl0316** [DTStack/flinkx#228]
![image](https://user-images.githubusercontent.com/39455920/83835106-80367280-a722-11ea-8817-6a475b6aefd0.png)
配置断点续传时,restoreColumnIndex属性不生效,还是会使用restoreColumnName属性去reader的column里面查找,这导致,column以column:["id","name"]方式配置时,报
![image](https://user-images.githubusercontent.com/39455920/83835251-e3c0a000-a722-11ea-8299-9e3501afe059.png)这个错误

**Comment by kanata163** [comment]
@hzl0316 
目前这个地方的逻辑是根据restoreColumnName来获取断点续传的字段信息的
