### ISSUE TITLE
断点续传 ，checkpoint 无法生成

### ISSUE THREAD

**Issue by wgf515** [DTStack/flinkx#239]
18:20:54.531 [Source: oraclereader -> Sink: hdfswriter (1/1)] INFO com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction - Start initialize output format state
18:20:54.547 [Source: oraclereader -> Sink: hdfswriter (1/1)] INFO com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction - Is restored:false
18:20:54.547 [Source: oraclereader -> Sink: hdfswriter (1/1)] INFO com.dtstack.flinkx.streaming.api.functions.sink.DtOutputFormatSinkFunction - End initialize output format state
18:20:54.547 [Source: oraclereader -> Sink: hdfswriter (1/1)] INFO com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction - Start initialize input format state
18:20:54.549 [Source: oraclereader -> Sink: hdfswriter (1/1)] INFO com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction - Is restored:false
18:20:54.549 [Source: oraclereader -> Sink: hdfswriter (1/1)] INFO com.dtstack.flinkx.streaming.api.functions.source.DtInputFormatSourceFunction - End initialize input format state

日志中，显示isRestored ：false.
json配置如下：
"restore": {
				"isRestore": true,
				"isStream": false,
				"restoreColumnName": "ID",
				"maxRowNumForCheckpoint": 1
			},

**Comment by baoziaichiyu** [comment]
请问是怎么解决的

**Comment by felix273118** [comment]
同样遇到
