### ISSUE TITLE
carbondata-hadoop版本问题

### ISSUE THREAD

**Issue by zhihui-ge** [DTStack/flinkx#24]
项目中使用1.5.0-SNAPSHOT版本，mvnrepository找不到这个版本，只有如下版本：
![image](https://user-images.githubusercontent.com/17016370/49921365-4ba87880-fee8-11e8-98e4-d295aa99409a.png)

**Comment by yangsishu** [comment]
dev分支的是我们的开发分支，还不能完全用

**Comment by zhihui-ge** [comment]
master上面的

**Comment by demotto** [comment]
carbondata依赖包版本已经调整为1.5.1， 数据同步插件还在开发中
