### ISSUE TITLE
一次提交多个content批量跑任务怎么实现

### ISSUE THREAD

**Issue by shadowyy** [DTStack/flinkx#241]
由于涉及的表比较多，所以希望能在一次提交中提交所有字段，但我看代码基本上都是.getContent().get(0)的，是否有此类实现，或者能批量跑的功能

**Comment by lvyanquan** [comment]
暂时没有这个实现和功能。

**Comment by kanata163** [comment]
@shadowyy 
一个任务一个json脚本，如果你有批量跑的需求，可以自己写一个批量提交的shell脚本
