### ISSUE TITLE
 postgresql的 pgwal read方式有错误,执行官网的例子失败

### ISSUE THREAD

**Issue by shejiewei** [DTStack/flinkx#244]
flinkx/flinkx-pgwal/flinkx-pgwal-reader/src/main/java/com/dtstack/flinkx/pgwal/format/PgWalInputFormat.java 
将这个类的openInputFormat函数
    public void openInputFormat() throws IOException{
        executor = Executors.newFixedThreadPool(1);
        queue = new SynchronousQueue<>(true);
    }
修改为
   public void openInputFormat() throws IOException{
        super.openInputFormat();
        executor = Executors.newFixedThreadPool(1);
        queue = new SynchronousQueue<>(true);
    }就可以了.

**Comment by kanata163** [comment]
@shejiewei 
错误日志发一下

**Comment by bymzy** [comment]
确实这样，修改后就可以了。
不修改前是一直failed。 @kanata163
