### ISSUE TITLE
什么时候更新到flink1.11版本？

### ISSUE THREAD

**Issue by ceaserzh** [DTStack/flinkx#247]
什么时候更新到flink1.11版本？

**Comment by kanata163** [comment]
目前还没这个打算

**Comment by ceaserzh** [comment]
flink1.11 已经支持Hive streaming sink，带来 Flink streaming 的实时/准实时的能力。能更新到这个版本吗？

**Comment by kanata163** [comment]
@ceaserzh 
已支持
