### ISSUE TITLE
Flinkx是否支持中间数据转换？

### ISSUE THREAD

**Issue by zhtisi** [DTStack/flinkx#26]
比如说很多情况下，需求不仅是源数据库到目标数据库之间的简单复制，还有可能包括一些转换过程，常见的有格式转换、去重、聚合、连接等等，这些是否能够通过flinkx完成呢？

**Comment by yangsishu** [comment]
不能

**Comment by zhtisi** [comment]
> 不能

感谢您的回复！ 请问这块短期内是否有计划在做呢？

**Comment by yangsishu** [comment]
这块不是我们这个框架的方向

**Comment by yangsishu** [comment]
你可以看下我们连外的一个框架 jlogstash 这个可以

**Comment by zhtisi** [comment]
> 你可以看下我们连外的一个框架 jlogstash 这个可以

好的，谢谢您的回复！
