### ISSUE TITLE
flinx 中Main 类型 restartStrategy 策略错误

### ISSUE THREAD

**Issue by lookhua** [DTStack/flinkx#262]
configRestartStrategy(env, config);  // **这个函数设置了setRestartStrategy的策略**

        SpeedConfig speedConfig = config.getJob().getSetting().getSpeed();

        env.setParallelism(speedConfig.getChannel());
        env.setRestartStrategy(RestartStrategies.noRestart()); // **这行代码重置了RestartStrategy的策略**

**Comment by kanata163** [comment]
@lookhua 
感谢反馈，确认是bug，下次更新修复。

**Comment by yanghuaiGit** [comment]
最新代码已经修改
