### ISSUE TITLE
关于日志和job运行结果的问题。

### ISSUE THREAD

**Issue by chenaiyuan** [DTStack/flinkx#269]
现在我有这么一个疑问或者是困惑，比如我通过我的java代码提交一个任务让flinkx执行，我怎么能知道或者flinkx如何通知我，任务执行完了。然后执行的结果是什么？难道flinkx的日志么？日志存在问题是可能是n个job的日志混杂在一起的。

还有一个问题，现在是执行成功与否都会打印出结果，我在连hbase时，故意把zk的地址写错，然后看日志，flinkx是一直试图连接zk，而不会打印出执行结果的，所以我现在无法通过什么渠道，判断我一个任务是否执行完毕，或者成功与否。

能否提供一个思路，或者告知如何得到job的执行结果

**Comment by kanata163** [comment]
可以通过History Server
rest api：http://hostname:port/jobs/<jobid>
https://ci.apache.org/projects/flink/flink-docs-release-1.11/monitoring/historyserver.html

**Comment by chenaiyuan** [comment]
您好，您好像没理解我的意思，就算是这个，1.那local模式的怎么办？2.按照我说的，zk如果错了，他会一直反复尝试连接zk，不会报错的，那我就不能通过这个接口获取东西，或者就不能通过这接口的字段判断是否是成功，或者失败原因是什么。

**Comment by kanata163** [comment]
1、local模式只能从日志或者JVM进程去查询任务是否运行结束，但是任务运行结果是很难拿到的。生产环境不建议使用local模式，至少也应该使用standalone模式。
2、这个可能是个bug，离线数据源连不上任务应该要报错
