### ISSUE TITLE
请问JDBC 并发读的原理是什么？

### ISSUE THREAD

**Issue by DoveYoung** [DTStack/flinkx#27]
JDBC 读数据 通过 JdbcInputFormatBuilder.setParameterValues(Object[][] parameterValues)来配置并发读，就是原理不是很明白。只能看出sql 语句中 通过 where mod(splitKey, 并发数 N) = [0,1,2...N-1] 可以把结果集分成N份，其它的实现就不知道了。
哪位大佬有空，请帮忙理理实现思路。万分感谢！

**Comment by yangsishu** [comment]
就是通过数字 取模

**Comment by coolsummery** [comment]
> JDBC 读数据 通过 JdbcInputFormatBuilder.setParameterValues(Object[][] parameterValues)来配置并发读，就是原理不是很明白。只能看出sql 语句中 通过 where mod(splitKey, 并发数 N) = [0,1,2...N-1] 可以把结果集分成N份，其它的实现就不知道了。
> 哪位大佬有空，请帮忙理理实现思路。万分感谢！

我理解是这样的，首先会生成并发数N个subtask，然后每个task都会去所有的表中进行一次查询，类似这样
subtask1 执行 select * from  db1.tb1 where mod(splitKey,并发数N) = 1   
subtask2 执行 select * from  db1.tb1 where mod(splitKey,并发数N) = 2
subtask1 执行 select * from  db1.tb2 where mod(splitKey,并发数N) = 1   
subtask2 执行 select * from  db1.tb2 where mod(splitKey,并发数N) = 2
这样，单张表的查询次数就是N次。
