### ISSUE TITLE
读取和写入clickhouse，配置文件中填了password项，但是某些情况下发送到数据库的连接信息中丢失了password值，进而报如下截图中的错

### ISSUE THREAD

**Issue by wowiscrazy** [DTStack/flinkx#276]
![image](https://user-images.githubusercontent.com/52560741/93746012-040b6080-fc27-11ea-84e6-7a6eec20b869.png)

**Comment by lvyanquan** [comment]
某些情况是指该问题不是必现的吗？
如果你已经下载了源码，可以在ClickhouseUtil.getConnection这个地方看下是否传入了password。

**Comment by wowiscrazy** [comment]
> 某些情况是指该问题不是必现的吗？
> 如果你已经下载了源码，可以在ClickhouseUtil.getConnection这个地方看下是否传入了password。

下载的是1.8版本的源码，该版本下测试的时候该问题必现。ClickhouseUtil.getConnection此处传入了password值，但是发送到数据库的时候，password值丢失，为null。
