### ISSUE TITLE
Error: Could not find or load main class .opt.flink.flink.deps.lib.flink-table_2.11-1.10.0.jar

### ISSUE THREAD

**Issue by zhaoysg** [DTStack/flinkx#300]
本地启动 
Flink 1.10 
FlinkX 1.10

syncplugins  放入Flink 目录下
flinkx-launcher-1.6.jar  放在Flink lib目录下
flinkx 放在Flink bin目录 权限777

./bin/flinkx -mode local  \
                     -job /opt/flink/flink/deps/job/stream.json \
           -pluginRoot /opt/flink/flink/deps/syncplugins \
           -confProp "{\"flink.checkpoint.interval\":60000}"\

执行报错 nohup: appending output to ‘nohup.out’ 
Error: Could not find or load main class .opt.flink.flink.deps.lib.flink-table_2.11-1.10.0.jar

麻烦大佬帮忙看一下是什么问题。

**Comment by kanata163** [comment]
FlinkX启动脚本里面找的是lib目录下的所有jar包，而你lib是flink的lib目录，里面有一些flink的jar包，而这些jar包是没有主类的，所以就报错了，你可以使用如下的命令运行：
java -cp  /opt/flink/flink/deps/lib/flinkx-launcher-1.6.jar com.dtstack.flinkx.launcher.Launcher -mode local -job /opt/flink/flink/deps/job/stream.json -pluginRoot /opt/flink/flink/deps/syncplugins
