### ISSUE TITLE
canal-json使用问题

### ISSUE THREAD

**Issue by peigenxiao** [DTStack/flinkx#303]
测试环境：flink1.11.1
相关jar：flink-format-changelog-json-1.1.1、flink-connector-kafka_2.11-1.11.1.jar、flink-sql-connector-kafka_2.11-1.11.1.jar

canal-json有bug，如果原始canal日志data数据列有空值，canal-json就全部解析为空值
![image](https://user-images.githubusercontent.com/20840982/103971499-b6027480-51a5-11eb-8f95-7a90ddb97ba6.png)
![image](https://user-images.githubusercontent.com/20840982/103971510-bd298280-51a5-11eb-9abc-a8cd6c275747.png)

**Comment by kanata163** [comment]
flink CDC的问题请向flink官方社区反馈
