### ISSUE TITLE
是否支持binlog实时写入hive

### ISSUE THREAD

**Issue by PONYLEE** [DTStack/flinkx#319]
配置binlog写入hive各种报错，配置不通过，是否支持此中配置。
如果支持，烦请提供一下配置样例。

**Comment by yanghuaiGit** [comment]
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
            "table": ["schema.table"],
            "password": "passwd",
            "database": "schema",
            "port": 3306,
            "cat": "insert,update,delete",
            "host": "host",
            "jdbcUrl": "jdbc:mysql://host:3306/schema",
            "pavingData": true,
            "username": "user"
          },
          "name": "binlogreader"
        },
        "writer": {
          "parameter": {
            "writeMode": "overwrite",
            "partitionType": "DAY",
            "tablesColumn" : "{\"CDC\":[{\"type\":\"VARCHAR2\",\"key\":\"before_ID\",\"comment\":\"\"},{\"comment\":\"\",\"type\":\"VARCHAR2\",\"key\":\"after_ID\"},{\"comment\":\"\",\"type\":\"varchar\",\"key\":\"type\"},{\"comment\":\"\",\"type\":\"varchar\",\"key\":\"schema\"},{\"comment\":\"\",\"type\":\"varchar\",\"key\":\"table\"},{\"comment\":\"\",\"type\":\"bigint\",\"key\":\"ts\"}]}",
            "partition": "pt",
            "hadoopConfig": {
              "dfs.ha.namenodes.ns1": "nn1,nn2",
              "dfs.namenode.rpc-address.ns1.nn2": "host1:9000",
              "dfs.client.failover.proxy.provider.ns1": "org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider",
              "dfs.namenode.rpc-address.ns1.nn1": "host2:9000",
              "dfs.nameservices": "ns1"
            },
            "jdbcUrl": "jdbc:hive2://host1:10000/dev",
            "defaultFS": "hdfs://ns1",
            "fileType": "orc",
            "charsetName": "utf-8",
            "username": "admin"
          },
          "name": "hivewriter"
        }
      }
    ],
    "setting": {
      "restore": {
        "isRestore": true,
        "isStream": true
      }
      "speed": {
        "channel": 1
      }
    }
  }
}

需要替换host等配置即可
