### ISSUE TITLE
KafkaUtil设置消费模式的时候有错误

### ISSUE THREAD

**Issue by jlon** [DTStack/flinkx#323]
分支: 1.11
问题：KafkaUtil获取消费模式的时候(方法: geneConsumerProp)，StartupMode这里使用的switch,每个分支应该增加break。
 switch (mode){
            case EARLIEST:
                props.put("auto.offset.reset", "earliest");
                break;
            case LATEST:
                props.put("auto.offset.reset", "latest");
        }

**Comment by kanata163** [comment]
感谢反馈，这里漏掉了
