### ISSUE TITLE
Could not resolve dependencies for project com.dtstack.flinkx:flinkx-db2-core:jar:1.6: Failure to find com.ibm.db2:db2jcc:jar:3.72.44

### ISSUE THREAD

**Issue by killerwzb** [DTStack/flinkx#328]
Hi，i use "mvn install package" and get this error:
[ERROR] Failed to execute goal on project flinkx-db2-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-db2-core:jar:1.6: Failure to find com.ibm.db2:db2jcc:jar:3.72.44 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :flinkx-db2-core

Can you tell me how to resolve it ? thanks.

**Comment by kanata163** [comment]
看文档
![image](https://user-images.githubusercontent.com/35188210/107022954-f115b900-67e0-11eb-99d9-388f8c8f455e.png)

**Comment by deadwind4** [comment]
please, cd bin/ and ./install_jars.sh in terminal
