### ISSUE TITLE
yarn 模式不能正常执行

### ISSUE THREAD

**Issue by yelijun** [DTStack/flinkx#33]
![image](https://user-images.githubusercontent.com/3347175/53154421-b9160b00-35f5-11e9-802b-d21ff2a0108f.png)
使用 on yarn 模式的时候报错

yarn session 启动方式：
`./yarn-session.sh -n 4`

**Comment by yangsishu** [comment]
你这的查看下flink-conf 配置有没有问题

**Comment by yelijun** [comment]
只修改了 jobmanager.rpc.address localhost 换成了IP，其他配置没有修改过。
把IP换回 localhost后也试过 还是会这样

flink 版本是1.5.6

**Comment by yelijun** [comment]
测试过 flink example yarn session 是可以提交任务的
但是flinkx 的时候就是不行 

> 启动方式:
bin/flinkx -mode yarn  -job test.json -plugin /data/software/flinkx/plugins -flinkconf /data/software/flink-1.5.6/conf -yarnconf /etc/hadoop/conf
