### ISSUE TITLE
flinkx 运行  com.dtstack.flinkx.test.LocalTest  , 这个类似 报错了   KerberosUtil 找不到符合

### ISSUE THREAD

**Issue by ithjz** [DTStack/flinkx#365]
D:\flinkx-1.10_release\flinkx-core\src\main\java\com\dtstack\flinkx\authenticate\KerberosUtil.java:205:25
java: 找不到符号
  符号:   变量 KeyTab
  位置: 类 com.dtstack.flinkx.authenticate.KerberosUtil

flinkx 运行  com.dtstack.flinkx.test.LocalTest  , 这个类似 报错了   KerberosUtil 找不到符合

**Comment by wuyascnu** [comment]
请问你解决了吗

**Comment by deadwind4** [comment]
用1.12 试试
