### ISSUE TITLE
sync mysql to mysql occurs null 

### ISSUE THREAD

**Issue by yelijun** [DTStack/flinkx#37]
同步mysql数据 到 mysql数据，
被同步的表 字段有约束：not null（实际是空字符串）
同步到目标的时候报错：字段不能null

mysql to hive 也会这样

**Comment by yangsishu** [comment]
这个bug后续会修复掉

**Comment by yelijun** [comment]
这个是由于写 还是 读 做了转换导致的？
如果我这边要用，能做什么特殊处理 可以快速使用？
