### ISSUE TITLE
弱弱的问一下，什么时候可以支持dorisDB啊

### ISSUE THREAD

**Issue by jinyan2049** [DTStack/flinkx#437]
不知道什么时候可以支持dorisDB,造福我们广大etl工程师

**Comment by kanata163** [comment]
这段时间比较忙，后续我们会考虑的，当然，你也可以按照文档，参考一下其他插件，自己开发一个。
FlinkX插件相对于flink来说，开发起来是比较简单的

**Comment by deadwind4** [comment]
doris 已经在开发了
