### ISSUE TITLE
oracle插入语句异常

### ISSUE THREAD

**Issue by etcxy** [DTStack/flinkx#442]
我的oracle环境为 oracle11

oracle插入的时候，遇到如下错误信息：
```
Caused by: oracle.jdbc.OracleDatabaseException: ORA-00907: 缺失右括号
```

#### 具体环境：

> oracle创建语句
```sql
CREATE TABLE stu (
	id number ,
	name VARCHAR2 ( 20 ),
	school VARCHAR2 ( 20 ),
	nickname VARCHAR2 ( 20 ),
	age number  ,
	class_num number ,
	score DECIMAL ( 4, 2 ),
	phone number,
	email VARCHAR2 ( 64 ),
	ip VARCHAR2 ( 32 ),
	address  VARCHAR2 ( 300 )
);
```

> Flinkx sql [sink]
```sql
CREATE TABLE sink
(
    id INT
    , name STRING
    , school STRING
    , nickname STRING
    , age int
    , class_num int
    , score decimal(4,2)
    , phone bigint
    , email STRING
    , ip STRING
    , address STRING
    , primary key(id,name) NOT ENFORCED
) WITH (
      'connector' = 'oracle-x',
      'url' = 'jdbc:oracle:thin:@hadoop123:1521:orcl',
      'table-name' = 'ABC.STU',
      'username' = 'abc',
      'password' = 'asdfghj',
      'sink.allReplace' = 'true', -- 解释如下(其他rdb数据库类似)：默认：false
      'sink.parallelism' = '1'    -- 写入结果的并行度，默认：null
      );
```

> 生成的write sql 

```sql
MERGE INTO "ABC"."STU" T1 USING (
	SELECT
		: id "id", : name "name", : school "school", : nickname "nickname", : age "age", : class_num "class_num", : score "score", : phone "phone", : email "email", : ip "ip", : address "address" 
	FROM DUAL 
		) T2 ON (
		T1."id" = T2."id",                -- 这里的`,`，需要改成 `and `
		T1."name" = T2."name" 
	) 
	WHEN MATCHED THEN
UPDATE 
	SET T1."school" = T2."school",
	T1."nickname" = T2."nickname",
	T1."age" = T2."age",
	T1."class_num" = T2."class_num",
	T1."score" = T2."score",
	T1."phone" = T2."phone",
	T1."email" = T2."email",
	T1."ip" = T2."ip",
	T1."address" = T2."address" 
	WHEN NOT MATCHED THEN
	INSERT (
		"id",
		"name",
		"school",
		"nickname",
		"age",
		"class_num",
		"score",
		"phone",
		"email",
		"ip",
		"address" 
	)
VALUES
	(
		T2."id",
		T2."name",
		T2."school",
		T2."nickname",
		T2."age",
		T2."class_num",
		T2."score",
		T2."phone",
		T2."email",
		T2."ip",
		T2."address" 
	)
```

sql语法本身先是存在一个异常。
另外,双引号里字母的需要强制转换为大写，否则报异常

**Comment by kyo-tom** [comment]
join on 条件应该用 and 连接，这个会在下个版本修复。字段大小写问题您可以尝试将sql中的字段名改为大写。

**Comment by kyo-tom** [comment]
> 我的oracle环境为 oracle11
> 
> oracle插入的时候，遇到如下错误信息：
> 
> ```
> Caused by: oracle.jdbc.OracleDatabaseException: ORA-00907: 缺失右括号
> ```
> 
> #### 具体环境：
> > oracle创建语句
> 
> ```sql
> CREATE TABLE stu (
> 	id number ,
> 	name VARCHAR2 ( 20 ),
> 	school VARCHAR2 ( 20 ),
> 	nickname VARCHAR2 ( 20 ),
> 	age number  ,
> 	class_num number ,
> 	score DECIMAL ( 4, 2 ),
> 	phone number,
> 	email VARCHAR2 ( 64 ),
> 	ip VARCHAR2 ( 32 ),
> 	address  VARCHAR2 ( 300 )
> );
> ```
> 
>  > Flinkx sql [sink]
> 
> ```sql
> CREATE TABLE sink
> (
>     id INT
>     , name STRING
>     , school STRING
>     , nickname STRING
>     , age int
>     , class_num int
>     , score decimal(4,2)
>     , phone bigint
>     , email STRING
>     , ip STRING
>     , address STRING
>     , primary key(id,name) NOT ENFORCED
> ) WITH (
>       'connector' = 'oracle-x',
>       'url' = 'jdbc:oracle:thin:@hadoop123:1521:orcl',
>       'table-name' = 'ABC.STU',
>       'username' = 'abc',
>       'password' = 'asdfghj',
>       'sink.allReplace' = 'true', -- 解释如下(其他rdb数据库类似)：默认：false
>       'sink.parallelism' = '1'    -- 写入结果的并行度，默认：null
>       );
> ```
> 
>  > 生成的write sql
> 
> ```sql
> MERGE INTO "ABC"."STU" T1 USING (
> 	SELECT
> 		: id "id", : name "name", : school "school", : nickname "nickname", : age "age", : class_num "class_num", : score "score", : phone "phone", : email "email", : ip "ip", : address "address" 
> 	FROM DUAL 
> 		) T2 ON (
> 		T1."id" = T2."id",                -- 这里的`,`，需要改成 `and `
> 		T1."name" = T2."name" 
> 	) 
> 	WHEN MATCHED THEN
> UPDATE 
> 	SET T1."school" = T2."school",
> 	T1."nickname" = T2."nickname",
> 	T1."age" = T2."age",
> 	T1."class_num" = T2."class_num",
> 	T1."score" = T2."score",
> 	T1."phone" = T2."phone",
> 	T1."email" = T2."email",
> 	T1."ip" = T2."ip",
> 	T1."address" = T2."address" 
> 	WHEN NOT MATCHED THEN
> 	INSERT (
> 		"id",
> 		"name",
> 		"school",
> 		"nickname",
> 		"age",
> 		"class_num",
> 		"score",
> 		"phone",
> 		"email",
> 		"ip",
> 		"address" 
> 	)
> VALUES
> 	(
> 		T2."id",
> 		T2."name",
> 		T2."school",
> 		T2."nickname",
> 		T2."age",
> 		T2."class_num",
> 		T2."score",
> 		T2."phone",
> 		T2."email",
> 		T2."ip",
> 		T2."address" 
> 	)
> ```
> 
> sql语法本身先是存在一个异常。
> 另外,双引号里字母的需要强制转换为大写，否则报异常

join on 条件应该用 and 连接，这个会在下个版本修复。字段大小写问题您可以尝试将sql中的字段名改为大写。
