### ISSUE TITLE
[ERROR] Failed to execute goal on project flinkx-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-core:jar:1.12-SNAPSHOT: Failure to find com.dtstack.iceberg: iceberg-flink-runtime:jar:0.12.efaad97 in https://maven.aliyun.com/repository/spring-plugin was cached in the local repository, resolution will not be reattempted until the update inte rval of aliyunmaven has elapsed or updates are forced -> [Help 1]

### ISSUE THREAD

**Issue by wuyascnu** [DTStack/flinkx#453]
[ERROR] Failed to execute goal on project flinkx-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-core:jar:1.12-SNAPSHOT: Failure to find com.dtstack.iceberg:
iceberg-flink-runtime:jar:0.12.efaad97 in https://maven.aliyun.com/repository/spring-plugin was cached in the local repository, resolution will not be reattempted until the update inte
rval of aliyunmaven has elapsed or updates are forced -> [Help 1]

**Comment by deadwind4** [comment]
拉下最新的代码，已经没有这个问题了
