### ISSUE TITLE
有没有人测试过抽取速度如何，比如抽取mysql到mysql，1亿数据量需要多长时间

### ISSUE THREAD

**Issue by Horrypotter** [DTStack/flinkx#46]

**Comment by Horrypotter** [comment]
<img width="1986" alt="WeChatd58bc9ed24bf04fd4ca6363e627a1837" src="https://user-images.githubusercontent.com/10825818/56354236-cc181680-6205-11e9-83fa-550271270aa9.png">
我在服务器上跑的，总共26w多条数据，slots是4，超级慢啊！！！

**Comment by Horrypotter** [comment]
同样的数据和环境用datax就十几秒

**Comment by yangsishu** [comment]
你用的是那个版本

**Comment by yangsishu** [comment]
最近我们也在做性能测试，几十万条记录跑这么慢肯定是有问题的，能发下你任务的的json配置吗

**Comment by yelijun** [comment]
1亿多 30分钟左右（每条数据字节数小），如果每条数据内容多会更慢，看了数据，每秒900条左右

**Comment by Horrypotter** [comment]
从mysql往mysql抽取，速度正常；
从mysql往oushuDB抽取，就是超级慢；
原因可能是他这个数据库对inset貌似支持不好。用datax向oushuDB插入的时候使用的插件是GpdbWriter插件，这个插件使用了copy from 来代替insert into ，速度超快。
我看这里的插入都是用insert into来搞的，也许可以改为copy from

**Comment by yangsishu** [comment]
oushuDB 这个我们是没有测试过的
