### ISSUE TITLE
[ERROR] Failed to execute goal on project flinkx-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-core:jar:1.12-SNAPSHOT: Failed to collect dependencies at com.dtstack.iceberg:iceberg-flink-runtime:jar:0.12.efaad97: Failed to read artifact descriptor for com.dtstack.iceberg:iceberg-flink-runtime:jar:0.12.efaad97: Could not transfer artifact com.dtstack.iceberg:iceberg-flink-runtime:pom:0.12.efaad97 from/to aliyunmaven (https://maven.aliyun.com/repository/spring-plugin): /home/link/app/flinkx/E:\repository2\maven_repository/com/dtstack/iceberg/iceberg-flink-runtime/0.12.efaad97/iceberg-flink-runtime-0.12.efaad97.pom.part.lock (Permission denied) -> [Help 1]

### ISSUE THREAD

**Issue by wuyascnu** [DTStack/flinkx#460]
[ERROR] Failed to execute goal on project flinkx-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-core:jar:1.12-SNAPSHOT: Failed to collect dependencies at com.dtstack.iceberg:iceberg-flink-runtime:jar:0.12.efaad97: Failed to read artifact descriptor for com.dtstack.iceberg:iceberg-flink-runtime:jar:0.12.efaad97: Could not transfer artifact com.dtstack.iceberg:iceberg-flink-runtime:pom:0.12.efaad97 from/to aliyunmaven (https://maven.aliyun.com/repository/spring-plugin): /home/link/app/flinkx/E:\repository2\maven_repository/com/dtstack/iceberg/iceberg-flink-runtime/0.12.efaad97/iceberg-flink-runtime-0.12.efaad97.pom.part.lock (Permission denied) -> [Help 1]

**Comment by deadwind4** [comment]
现在没有这个问题

**Comment by wuyascnu** [comment]
好的，谢谢
