### ISSUE TITLE
oracle jar包版本问题。现在此com.github.noraui:ojdbc8:jar:12.2.0.1 已经找不到了

### ISSUE THREAD

**Issue by JackYu965** [DTStack/flinkx#52]
[INFO] ------------------------------------------------------------------------
### [ERROR] Failed to execute goal on project flinkx-oracle-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-oracle-core:jar:1.6: Could not find artifact com.oracle.jdbc:ojdbc8:jar:12.2.0.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :flinkx-oracle-core

**Comment by lijiangbo** [comment]
> [INFO] ------------------------------------------------------------------------
> 
> ### [ERROR] Failed to execute goal on project flinkx-oracle-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-oracle-core:jar:1.6: Could not find artifact com.oracle.jdbc:ojdbc8:jar:12.2.0.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :flinkx-oracle-core

你用的是哪个分支

**Comment by lijiangbo** [comment]
> [INFO] ------------------------------------------------------------------------
> 
> ### [ERROR] Failed to execute goal on project flinkx-oracle-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-oracle-core:jar:1.6: Could not find artifact com.oracle.jdbc:ojdbc8:jar:12.2.0.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :flinkx-oracle-core

临时解决办法：
https://github.com/DTStack/flinkx/tree/v1.5.0_dev/jars

**Comment by mnuestc** [comment]
遇到相同问题，现在有解决办法吗
