### ISSUE TITLE
hdfs,hive的orc格式写入bug

### ISSUE THREAD

**Issue by hellochueng** [DTStack/flinkx#526]
**Describe the bug**
当使用hdfs或者hive的写入插件时，配置写入的文件格式为orc会报文件找不到的问题

**To Reproduce**
![image](https://user-images.githubusercontent.com/29030883/138066076-90a9b15f-e245-4a56-b60f-bf63c07cc262.png)
BaseHdfsOutputFormat.getCurrentFileSize方法会抛出file not found exception
debug跟踪源码分析
![image](https://user-images.githubusercontent.com/29030883/138066374-bd0c7b42-3297-4f75-aef3-0234a6378002.png)
BaseFileOutputFormat的checkCurrentFileSize方法在检查文件的大小后根据条件会flushdata到文件
flushdata方法会创建文件并且把数据输出到文件
但是在此之前调用getCurrentFileSize方法时，文件是没有生成的，所以会抛出异常
**Expected behavior**
![image](https://user-images.githubusercontent.com/29030883/138066865-d253596f-9fb7-4987-ae1b-3a95978ea7c1.png)
我目前是直接把异常给抓取然后flushdata，这样会让MaxFileSize这个配置参数失效
希望官方能尽快修复

**Comment by kanata163** [comment]
hadoop版本：2.7.7，这一行生成的

![image](https://user-images.githubusercontent.com/35188210/138205836-79f681cb-1de0-4f71-ba2f-080cb088e6a6.png)

![image](https://user-images.githubusercontent.com/35188210/138205910-227336c5-4ced-40d7-aa26-5cde6f751f6c.png)

**Comment by hellochueng** [comment]
这个和hadoop版本没关系，我的是hadoop3的版本

**Comment by hellochueng** [comment]
2021/11/11编译master分支代码，尝试写入orc文件成功。
