### ISSUE TITLE
db2 jar包问题，现在此com.ibm.db2:db2jcc:jar:3.72.44找不到

### ISSUE THREAD

**Issue by JackYu965** [DTStack/flinkx#53]
[ERROR] Failed to execute goal on project flinkx-db2-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-db2-core:jar:1.6: Could not find artifact com.ibm.db2:db2jcc:jar:3.72.44 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :flinkx-db2-core

**Comment by lijiangbo** [comment]
> [ERROR] Failed to execute goal on project flinkx-db2-core: Could not resolve dependencies for project com.dtstack.flinkx:flinkx-db2-core:jar:1.6: Could not find artifact com.ibm.db2:db2jcc:jar:3.72.44 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR] mvn -rf :flinkx-db2-core

临时解决办法：
https://github.com/DTStack/flinkx/tree/v1.5.0_dev/jars
