### ISSUE TITLE
增加flinkx-hudi-writer插件

### ISSUE THREAD

**Issue by renxiaoyao** [DTStack/flinkx#554]
Apache Hudi使得能在hadoop兼容的存储之上存储大量数据，同时它还提供两种原语，使得除了经典的批处理之外，还可以在数据湖上进行流处理。这两种原语分别是：Update/Delete记录，变更流。
Flink hudi支持的表类型是：Copy On Write表。

**Comment by dik111** [comment]
+1

**Comment by yangsishu** [comment]
已经合并

**Comment by dik111** [comment]
> 已经合并

文档什么时候能更新呢？
