### ISSUE TITLE
Carbondata writer 看现在用的1.5的版本， 会向下兼容carbondata1.3版本吗

### ISSUE THREAD

**Issue by HeineG** [DTStack/flinkx#56]
新手carbondata, 不知道写carbondata文件结构是怎样的，下载下来测试异常：
java.lang.RuntimeException: java.lang.InterruptedException: org.apache.carbondata.core.datastore.exception.CarbonDataWriterException: org.apache.carbondata.core.datastore.exception.CarbonDataWriterException
	at com.dtstack.flinkx.carbondata.writer.CarbonOutputFormat.closeInternal(CarbonOutputFormat.java:261)
	at com.dtstack.flinkx.outputformat.RichOutputFormat.close(RichOutputFormat.java:346)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.close(OutputFormatSinkFunction.java:96)
	at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.close(AbstractUdfStreamOperator.java:109)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.closeAllOperators(StreamTask.java:438)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:323)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:712)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException: org.apache.carbondata.core.datastore.exception.CarbonDataWriterException: org.apache.carbondata.core.datastore.exception.CarbonDataWriterException
	at org.apache.carbondata.hadoop.api.CarbonTableOutputFormat$CarbonRecordWriter.close(CarbonTableOutputFormat.java:456)
	at com.dtstack.flinkx.carbondata.writer.recordwriter.AbstractRecordWriter.closeRecordWriter(AbstractRecordWriter.java:108)
	at com.dtstack.flinkx.carbondata.writer.recordwriter.AbstractRecordWriter.close(AbstractRecordWriter.java:174)
	at com.dtstack.flinkx.carbondata.writer.CarbonOutputFormat.closeInternal(CarbonOutputFormat.java:259)
	... 8 more

**Comment by lijiangbo** [comment]
> 新手carbondata, 不知道写carbondata文件结构是怎样的，下载下来测试异常：
> java.lang.RuntimeException: java.lang.InterruptedException: org.apache.carbondata.core.datastore.exception.CarbonDataWriterException: org.apache.carbondata.core.datastore.exception.CarbonDataWriterException
> at com.dtstack.flinkx.carbondata.writer.CarbonOutputFormat.closeInternal(CarbonOutputFormat.java:261)
> at com.dtstack.flinkx.outputformat.RichOutputFormat.close(RichOutputFormat.java:346)
> at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.close(OutputFormatSinkFunction.java:96)
> at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
> at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.close(AbstractUdfStreamOperator.java:109)
> at org.apache.flink.streaming.runtime.tasks.StreamTask.closeAllOperators(StreamTask.java:438)
> at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:323)
> at org.apache.flink.runtime.taskmanager.Task.run(Task.java:712)
> at java.lang.Thread.run(Thread.java:745)
> Caused by: java.lang.InterruptedException: org.apache.carbondata.core.datastore.exception.CarbonDataWriterException: org.apache.carbondata.core.datastore.exception.CarbonDataWriterException
> at org.apache.carbondata.hadoop.api.CarbonTableOutputFormat$CarbonRecordWriter.close(CarbonTableOutputFormat.java:456)
> at com.dtstack.flinkx.carbondata.writer.recordwriter.AbstractRecordWriter.closeRecordWriter(AbstractRecordWriter.java:108)
> at com.dtstack.flinkx.carbondata.writer.recordwriter.AbstractRecordWriter.close(AbstractRecordWriter.java:174)
> at com.dtstack.flinkx.carbondata.writer.CarbonOutputFormat.closeInternal(CarbonOutputFormat.java:259)
> ... 8 more

麻烦发下你的任务json，还有，错误日志只有这些吗？

**Comment by HeineG** [comment]
日志只有这些，
json这样，我做了点修改
{
    "job":{
        "content":[
            {
                "reader":{
                    "parameter":{
                        "scanBatchSize":10000,
                        "password":"",
                        "column":[
                            {
                                "name":"ID",
                                "type":"VARCHAR"
                            },
                            {
                                "name":"TRANSID",
                                "type":"VARCHAR"
                            }
                        ],
                        "hbaseConfig":{
                            "driverClass":"org.apache.phoenix.jdbc.PhoenixDriver",
                            "jdbcUrl":"jdbc:phoenix:192.168.40.183,192.168.40.184,192.168.40.185:2181"
                        },
                        "username":"",
                        "sql":"select
							TRANSID,
							TRANSTIME
							from FUND.ODS_WUFPS_SUMMONS_his
							WHERE TO_CHAR(TO_DATE(STARTTIME,'yyyy-MM-dd HH:mm:ss'),'yyyyMMdd') = '20190512'
							and TO_CHAR(TO_DATE(ENDTIME,'yyyy-MM-dd HH:mm:ss'),'yyyyMMdd') > '20190512'"
                    },
                    "name":"phoenixreader"
                },
                "writer":{
                    "parameter":{
                        "path":"hdfs://nameservice1/opt/carbon/carbonstore/test/ods_wufps_summons_test2",
                        "fileName":"ods_wufps_summons_test2",
                        "hadoopConfig":{
                            "dfs.ha.namenodes.nameservice1":"namenode250,namenode346",
                            "dfs.namenode.rpc-address.nameservice1.namenode250":"skudcdev02:8020",
                            "dfs.namenode.rpc-address.nameservice1.namenode346":"skudcdev03:8020",
                            "dfs.nameservices":"nameservice1",
                            "dfs.client.failover.proxy.provider.nameservice1":"org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider"
                        },
                        "column":[
                            {
                                "name":"id",
                                "type":"string"
                            },
                            {
                                "name":"transid",
                                "type":"string"
                            }
                        ],
                        "defaultFS":"hdfs://nameservice1",
                        "writeMode":"overwrite",
                        "table":"ods_wufps_summons_test2",
                        "database":"test"
                    },
                    "name":"carbondatawriter"
                }
            }
        ],
        "setting":{
            "errorLimit":{
                "record":10000,
                "percentage":100
            },
            "speed":{
                "bytes":0,
                "channel":3
            }
        }
    }
}

**Comment by HeineG** [comment]
debug进去这个异常， 看不懂，大神请教一下：

![image](https://user-images.githubusercontent.com/31837479/57774072-209eab00-774c-11e9-8ed4-2c327a29e97f.png)

**Comment by yangsishu** [comment]
carbondata1.3版本 没测试过

**Comment by HeineG** [comment]
多谢回复，有个问题请教一下：
我用了一个环境是1.5.2版本的， 执行成功，文件写上去了
![image](https://user-images.githubusercontent.com/31837479/58012223-94fb9480-7b26-11e9-8b5d-b9d70ac0a3ef.png)
但是用spark shell去查询的时候，查询不出数据， 我看了代码执行是走hive区分那个类，请问查询是可以在哪里设置查询数据的类型吗？谢谢!
![image](https://user-images.githubusercontent.com/31837479/58012359-de4be400-7b26-11e9-9255-7cce12fb0a7f.png)
