### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LY-GO** [DTStack/flinkx#563]
``## General Question

![Snipaste_2021-12-10_15-47-41](https://user-images.githubusercontent.com/67543312/145536851-2cf9166f-fbd3-4152-8bbe-eb5c5eda77d2.png)
版本:
flink 1.12.5
flinkx 12.0
![Snipaste_2021-12-10_15-49-25](https://user-images.githubusercontent.com/67543312/145536985-0586eff1-9f42-41dc-9e0e-a640d7f15301.png)

Question:

存到数据库的数据是rowData前三个字段,数据不对,因为rowData为8个元素; toExternalConverters这个数组只有三个元素

#json模板:
[mysql-binlog.txt](https://github.com/DTStack/flinkx/files/7708509/mysql-binlog.txt)

**Comment by LY-GO** [comment]
{
  "job": {
    "content": [
      {
        "reader": {
          "parameter": {
	    "schema" : "flink",
            "table": ["source"],
            "password": "root",
            "port": 3307,
            "cat": "insert,delete,update",
            "host": "192.168.193.1",
            "jdbcUrl": "jdbc:mysql://192.168.193.1:3307/flink?useSSL=false",
             "start" : {
           
          },
            "splitUpdate" : true,
            "pavingData": true,
            "username": "root",
            "column": [
              {
                "name": "id",
                "type": "VARCHAR"
              },
              {
                "name": "age",
                "type": "VARCHAR"
              },
              {
                "name": "username",
                "type": "VARCHAR"
              }
            ]

          },
          "name": "binlogreader"
        },

        "writer": {
          "name": "mysqlwriter",
          "parameter": {
            "username": "root",
            "password": "root",
            "connection": [
              {
                "jdbcUrl":  "jdbc:mysql://192.168.193.1:3307/flink?useSSL=false",
                "table": ["target"],
                "schema": "flink"
              }
            ],
            "writeMode": "insert",
            "column": [
              {
                "name": "id",
                "type": "VARCHAR"
              },
              {
                "name": "age",
                "type": "VARCHAR"
              },
              {
                "name": "username",
                "type": "VARCHAR"
              }
            ]
          }
        }
      }
    ],
    "setting": {
      "speed": {
        "bytes": 0,
        "channel": 1
      }
    }
  }
}

**Comment by WTZ468071157** [comment]
![image](https://user-images.githubusercontent.com/35768015/145950002-96db91ca-f8b5-4907-819f-9b850a0b6bc9.png)

binlog的数据结构较为特殊，它不像mysql reader那样解析出来的数据是key - value的形式，而是带有其他信息的event sink，所以不能直接对接mysql。
PS：这功能我们内部在开发中。

**Comment by LY-GO** [comment]
> ![image](https://user-images.githubusercontent.com/35768015/145950002-96db91ca-f8b5-4907-819f-9b850a0b6bc9.png)
> 
> binlog的数据结构较为特殊，它不像mysql reader那样解析出来的数据是key - value的形式，而是带有其他信息的event sink，所以不能直接对接mysql。 PS：这功能我们内部在开发中。

那支持mysql-binlog到hbase咩
