### ISSUE TITLE
flinkx 1.12 BUILD FAILURE

### ISSUE THREAD

**Issue by nuclearwu** [DTStack/flinkx#566]
Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.4.2:check (spotless-check) on project flinkx-core: Execution spotless-check of goal com.diffplug.spotless:spotless-maven-plugin:2
.4.2:check failed: Unable to resolve dependencies: Failed to collect dependencies at com.google.googlejavaformat:google-java-format:jar:1.7 -> com.google.errorprone:javac-shaded:jar:9+181-r4173-1: Failed to
 read artifact descriptor for com.google.errorprone:javac-shaded:jar:9+181-r4173-1: Could not transfer artifact com.google.errorprone:javac-shaded:pom:9+181-r4173-1 from/to alimaven (http://maven.aliyun.com
/nexus/content/groups/public/): Access denied to: http://maven.aliyun.com/nexus/content/groups/public/com/google/errorprone/javac-shaded/9+181-r4173-1/javac-shaded-9+181-r4173-1.pom -> [Help 1]

**Comment by nuclearwu** [comment]
![image](https://user-images.githubusercontent.com/37976659/146333344-a2709a49-7716-4604-8d7d-0c52a7726331.png)

**Comment by deadwind4** [comment]
disable aliyun maven mirror to try it again
