### ISSUE TITLE
[flinkx-connector] 查询decimal丢失小数点后数字问题

### ISSUE THREAD

**Issue by liukunyuan** [DTStack/flinkx#575]
如何复现此bug
1、创建1张mysql表，value1 decimal(10,2)
在表1存value1=1.08.然后通过
CREATE TABLE source (value1 decimal ) xxxxxx ;去查询会丢失小数点后数字
如果使用
CREATE TABLE source (value1 decimal(10,2)) xxxxxx ;去查询，不会丢失小数点后数字

**Comment by liukunyuan** [comment]
在这3个类中，都受此bug影响
<img width="286" alt="f66d619e01eeef97495ffc150d0a033" src="https://user-images.githubusercontent.com/50513095/147437260-b986b020-5521-4145-b8fd-cdfca290db81.png">

**Comment by deadwind4** [comment]
你不设置的话，Flink默认应该是 DECIMAL(10, 0)

**Comment by liukunyuan** [comment]
<img width="444" alt="1640657299849_3073C4EE-AE0B-4a46-B8E3-728F4D1A6950" src="https://user-images.githubusercontent.com/50513095/147520050-edcdcbf7-cbe6-442f-be08-bf90ed115673.png">

**Comment by liukunyuan** [comment]
通过这种方式解决的

**Comment by deadwind4** [comment]
这不是Bug，这样修改DDL中显示配置的精度将失效，而且会不会引入其他Flink问题我还不知道。
