### ISSUE TITLE
postgre jdbc upsert mode has not been filtered primary key..

### ISSUE THREAD

**Issue by chaozwn** [DTStack/flinkx#599]
**Describe the bug**
postgre jdbc upsert mode has not been filtered primary key..

![image](https://user-images.githubusercontent.com/51357674/153114366-caa27d82-14fe-4f04-94e7-b9f56de48111.png)
![image](https://user-images.githubusercontent.com/51357674/153114376-2559705c-cf43-4528-b238-3b24209ef6f7.png)

i will fix it. please assign to me.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by Su1024** [comment]
#600 can fix this issues

**Comment by WTZ468071157** [comment]
merged pr.
