### ISSUE TITLE
运行json报错

### ISSUE THREAD

**Issue by acChris** [DTStack/flinkx#606]
分支：1.12
命令：
官方的，和如下的命令都报相同的错误
```
./bin/flinkx \
         -mode local \
         -jobType sync \
         -job flinkx-examples/json/stream/stream.json \
         -flinkxDistDir flinkx-dist
```

**报错如下：**
```
错误: 找不到或无法加载主类 .home.fs123.Desktop.flinkx.lib.flinkx-launcher-1.6.jar
```

大佬求解

**Comment by WTZ468071157** [comment]
你这是不是自己改动过代码了呢？我这验证的没有问题呐

**Comment by acChris** [comment]
没改动过

**Comment by acChris** [comment]
没改动过呢

**Comment by acChris** [comment]
![image](https://user-images.githubusercontent.com/55875617/153794266-227d4049-baf8-4036-85df-cd651c5028b0.png)
这个 maven 有时候加载不到依赖，可以帮忙解释一下吗？

**Comment by acChris** [comment]
@WTZ468071157 请问你用的是master分支吗？我再拉取最新代码尝试一遍

**Comment by acChris** [comment]
直接把 home.fs123.Desktop.flinkx.lib.flinkx-launcher-1.6.jar 删掉即可

**Comment by zhuohb** [comment]
-flinkxDistDir flinkx-dist
路径写完整就行
