### ISSUE TITLE
使FlinkX支持自定义参数传递

### ISSUE THREAD

**Issue by 15207126400** [DTStack/flinkx#607]
**我们的业务场景主要是通过flinkx采集数据进行数据处理及后续的分析应用，由于业务需要，每一个flinkx任务均需要携带一个任务源ID向下游队列传递，因此对源码进行了拓展，使部分业务支持传递自定义参数。**

- 源码拓展
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/32918639/153791961-d93ce5bc-7629-4f7a-8e49-ee832583dab7.png">
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/32918639/153792025-6dce18d4-6668-468e-a832-c5e9a1ce2add.png">

- 配置文件定义参数
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/32918639/153792498-6d595202-1955-4cef-ac4c-7de6c2b77afe.png">

- 效果展示
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/32918639/153792749-1cb585ae-ea87-4660-a8d3-3ea7db0e2a71.png">
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/32918639/153792888-39d42a50-13a7-42dc-b23b-52caa1dea913.png">

- 说明
目前支持自定义参数传递的插件Jar包括实时采集（MySQL binlog、SqlServer cdc、Oracle logminer、Kafka、Mqtt），离线采集的MySQL。
目前业务已经稳定在线运营，也是有部分源码改动的原因，一直没有更新最新的FlinkX版本，开发版本为flinkx-1.10.4_release。

**Comment by WTZ468071157** [comment]
个人感觉，这个功能有点偏业务了，不够通用。

**Comment by WTZ468071157** [comment]
由于业务需要，每一个flinkx任务均需要携带一个任务源ID向下游队列传递

假设其他用户不需要任务源ID，而是其他的ID，是不是又需要改动代码，来适应其业务逻辑呢？FlinkX本身不应该和业务强耦合

**Comment by 15207126400** [comment]
确实是有一定的业务性，主要也是考虑支持传递一个业务性参数。并非是强耦合，如果用户不需要，对FlinkX本身没有任何影响。

**Comment by 15207126400** [comment]
> 由于业务需要，每一个flinkx任务均需要携带一个任务源ID向下游队列传递
> 
> 假设其他用户不需要任务源ID，而是其他的ID，是不是又需要改动代码，来适应其业务逻辑呢？FlinkX本身不应该和业务强耦合

如果用户需要的是其他的ID也无需改动代码的，这里提供的就是一个自定义参数customField，至于用户实际上需要传递的到底是什么，完全由他自己决定，接收到参数后，他刻可以做自己的业务处理。

**Comment by 15207126400** [comment]
感谢回复。
