### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by wujieaiyan** [DTStack/flinkx#61]
[](url)

本地调试错误
![image](https://user-images.githubusercontent.com/22367785/59330732-d695ee80-8d24-11e9-9b71-3dc9f276af3e.png)

**Comment by wujieaiyan** [comment]
服务器上运行：
./bin/flinkx -mode yarn -job /opt/flinkx/flinkx-examples/examples/mysql_to_mysql.json -plugin /opt/flinkx/plugins -flinkconf /opt/flinkx/flinkconf/ -yarnconf /opt/flinkx/flinkconf
错误如下：
![image](https://user-images.githubusercontent.com/22367785/59330839-270d4c00-8d25-11e9-8380-74a86a58bbec.png)

**Comment by yangsishu** [comment]
仔细看下github的介绍，本地debug在idea上也要填参数的；yarn 模式，是flink要预先在yarn 上启动yarn-session模式的

**Comment by wujieaiyan** [comment]
yarn-session 已经启动

**Comment by wujieaiyan** [comment]
![image](https://user-images.githubusercontent.com/22367785/59488747-ee02e200-8eb2-11e9-9cff-f04df0326a84.png)

**Comment by yangsishu** [comment]
你的flink是什么版本，我们现在用的是flink1.5.4版本的，flinkx的版本也要是1.5.x版本的，这个版本要对应的

**Comment by wujieaiyan** [comment]
集群是1.7.2 分支是1.70的

**Comment by gk0916** [comment]
yarn模式，且是zookeeper高可用配置下。代码中缺少高可用信息的配置。详见v1.5.2分支下的ClusterClientFactory类的更新内容
