### ISSUE TITLE
用session方式提交，需要把插件拷贝到每个节点才能运行吗

### ISSUE THREAD

**Issue by easonpeng** [DTStack/flinkx#67]
org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: ch.qos.logback.classic.Logger
ClassLoader info: URL ClassLoader:
file: '/data3/yarn/nm/usercache/root/appcache/application_1544768545362_0843/blobStore-8adb0e17-dc6d-4483-9bf3-c9e17218fff4/job_0be51bf30c1876bac50876dcda78602d/blob_p-09ff3108ffc810d694ec5cf7e4370b8ea3b81890-68d3a95ce8b51258378b6a941c71e486' (valid JAR)
file: '/data/software/flinkx/plugins/mysqlreader/flinkx-mysql-reader.jar' (valid JAR)
file: '/data/software/flinkx/plugins/hdfswriter/flinkx-hdfs-writer.jar' (valid JAR)
file: '/data/software/flinkx/plugins/common/flinkx-rdb.jar' (valid JAR)
Class not resolvable through given classloader.

**Comment by gk0916** [comment]
我测试的结果是这样的。需要datanode节点拷贝相应文件

**Comment by yangsishu** [comment]
是的
