### ISSUE TITLE
Failure to find com.ibm.db2:db2jcc:jar:3.72.44

### ISSUE THREAD

**Issue by jihr** [DTStack/flinkx#76]
编译打包报如题的错误

**Comment by lawrencehjf** [comment]
> 编译打包报如题的错误

请问您是在哪找到3.72.44的db2jcc:jar的呢，中央仓库和aliyun貌似都找不到对应版本。

**Comment by lawrencehjf** [comment]
https://www.ibm.com/support/pages/db2-jdbc-driver-versions-and-downloads
