### ISSUE TITLE
请问有交流沟通群么

### ISSUE THREAD

**Issue by lawrencehjf** [DTStack/flinkx#82]
我们最近要做数据集成的项目，考虑调研下flinkx，支持完善的话数据采集同步就想主力使用flinkx，打算等熟练使用上，后期参与回馈项目。
现在的问题是：看完 readme 过后，感觉初步能够满足我们的项目需求，但是你对于多种数据源的采集同步支持，还有待进一步确认【比如数据源头有很多种类型 FTP、EXCEL、Mysql、SqlServer、Oracle、Kafka、日志、RestApi，等等，是否都能很好的支持流批采集呢】，谢谢。

**Comment by yangsishu** [comment]
没有沟通群，批和流的采集都用flinkx框架都可以的；现在的flinkx里的插件大部分都是离线采集；binglog，kafka是实时采集；这个自己都可以扩展的

**Comment by lawrencehjf** [comment]
> 没有沟通群，批和流的采集都用flinkx框架都可以的；现在的flinkx里的插件大部分都是离线采集；binglog，kafka是实时采集；这个自己都可以扩展的

恩，谢谢。
        我们集成的架构设计中间有一个MQ的缓存，方便于落仓和消费并writer前作进一步预加工，理论上是可以，就是不知道使用flinkx来串联前后的 读+预加工+写 逻辑并实现界面化的配置运行监控上，是否有一些潜在的较高风险是flinkx没有cover到，但需要我们自己来处理解决掉的呢【按照之前构想的，吞吐、读写failover control 监控、限流貌似都有支持到，单不清楚是否有没烫过要注意的坑，还请多多指点，谢谢】

**Comment by pierre94** [comment]
#29 

建了一个非官方的学习交流群，感兴趣可以一起学习交流哈

![image](https://user-images.githubusercontent.com/12579749/66541095-ae968a80-eb60-11e9-9b86-6523729c7461.png)

**Comment by curruy** [comment]
有群就好了

**Comment by fuyun2024** [comment]
交流群能再发一下链接么？

**Comment by huangrunxing-code** [comment]
失效了

**Comment by huangrunxing-code** [comment]
> #29
> 
> 建了一个非官方的学习交流群，感兴趣可以一起学习交流哈
> 
> ![image](https://user-images.githubusercontent.com/12579749/66541095-ae968a80-eb60-11e9-9b86-6523729c7461.png)

失效了

**Comment by pierre94** [comment]
> > #29
> > 建了一个非官方的学习交流群，感兴趣可以一起学习交流哈
> > ![image](https://user-images.githubusercontent.com/12579749/66541095-ae968a80-eb60-11e9-9b86-6523729c7461.png)
> 
> 失效了

![85CE8B9A-FE00-4D60-AB16-DBE69DED1B84](https://user-images.githubusercontent.com/12579749/69241354-9a22c480-0bd9-11ea-97fb-3d73e1fad886.jpeg)刷新了，圈子在不断扩大

**Comment by Clarencezero** [comment]
二维码失效了

**Comment by shierad123** [comment]
> [＃29](https://github.com/DTStack/flinkx/issues/29)
> 
> 建了一个非官方的学习交流群，认知可以一起学习交流哈
> 
> ![图片](https://user-images.githubusercontent.com/12579749/66541095-ae968a80-eb60-11e9-9b86-6523729c7461.png)

您好 , 二维码可以再发一下吗 谢谢

**Comment by pierre94** [comment]
> > [＃29](https://github.com/DTStack/flinkx/issues/29)
> > 建了一个非官方的学习交流群，认知可以一起学习交流哈
> > ![图片](https://user-images.githubusercontent.com/12579749/66541095-ae968a80-eb60-11e9-9b86-6523729c7461.png)
> 
> 您好 , 二维码可以再发一下吗 谢谢

群的有效期太短了，直接加我微信吧 hell0_b34r

**Comment by lijiangbo** [comment]
![image](https://user-images.githubusercontent.com/11881814/76816790-22d60800-683c-11ea-8755-f48ddaeb3a1b.png)
官方交流群

**Comment by zhaoysg** [comment]
还有 交流群吗请教大家一些问题
