### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/flinkx#84]
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.6:revision (default) on project flinkx-core: Could not complete Mojo executio
n... Error: Could not get HEAD Ref, are you sure you have some commits in the dotGitDirectory? -> [Help 1]

**Comment by lijiangbo** [comment]
打包命令发下

**Comment by momisabuilder** [comment]
从release下载的源码1.8.1.zip，然后解压，引入idea中，执行命令
mvn clean package -Dmaven.test.skip

**Comment by lijiangbo** [comment]
这个问题我们后面会解决的，你先用git把项目clone到本地，再用mvn打包

**Comment by kanata163** [comment]
已解决
