### ISSUE TITLE
编译的时候jar下载问题

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/flinkx#85]
<dependencies>
        <dependency>
            <groupId>com.ibm.db2</groupId>
            <artifactId>db2jcc</artifactId>
            <version>3.72.44</version>
        </dependency>
    </dependencies>

**Comment by momisabuilder** [comment]
<dependencies>
        <dependency>
            <groupId>com.ibm.db2</groupId>
            <artifactId>db2jcc</artifactId>
            <version>3.72.44</version>
        </dependency>
    </dependencies>

**Comment by lijiangbo** [comment]
https://github.com/DTStack/flinkx/tree/1.8.1/jars

**Comment by momisabuilder** [comment]
你好，没有standalone的启动吗？




------------------ 原始邮件 ------------------
发件人: "jiangbo"<notifications@github.com>; 
发送时间: 2019年10月10日(星期四) 中午12:56
收件人: "DTStack/flinkx"<flinkx@noreply.github.com>; 
抄送: "烦不烦 "<1518386192@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [DTStack/flinkx] 编译的时候jar下载问题 (#85)




https://github.com/DTStack/flinkx/tree/1.8.1/jars

**Comment by loftyet** [comment]
I also have this `gbase-8.3.81.53.jar.lastUpdated` issue. It means the `gbase` doesn't work for loading.

**Comment by kanata163** [comment]
https://github.com/DTStack/flinkx/blob/1.8.2/jars/gbase-8.3.81.53.jar
