### ISSUE TITLE
命令启动报错

### ISSUE THREAD

**Issue by momisabuilder** [DTStack/flinkx#86]
[root@xy01 flinkx]# ./bin/flinkx -mode local -job /opt/software/flinkx/flinkx-examples/examples/mysql_to_mysql.json  -pluginRoot /opt/software/flinkx/plugins/ -flinkconf /opt/software/flinkx-r1.8.1/flinkconf/flink-conf.yaml
: No such file or directory

**Comment by momisabuilder** [comment]
[root@xy01 flinkx]# ./bin/flinkx -mode local -job /opt/software/flinkx/flinkx-examples/examples/mysql_to_mysql.json -pluginRoot /opt/software/flinkx/plugins/ -flinkconf /opt/software/flinkx-r1.8.1/flinkconf/flink-conf.yaml
: No such file or directory

**Comment by yangsishu** [comment]
检查下上面传的目录存不存在，报错很明显
