### ISSUE TITLE
请问是否 支持mysql_to_kafaka

### ISSUE THREAD

**Issue by lawrencehjf** [DTStack/flinkx#88]
您好，如下是我自己修改配置的mysql_to_kafaka采集过程，经过调试发现没有出错，也有回显采集结果正常，但是kafka查不到消息，请问我这种方式现在支持么，如果不支持，我需要从哪一步入手来去修改支持，谢谢。
     线贴出我的配置和采集结果如下：
   
————————————————————————————————————————————
     配置文件：

{
  "job" : {
    "setting": {
      "speed": {
        "channel": 1
      },
      "errorLimit": {
        "record": 0,
        "percentage": 0.02
      },
      "restore": {
        "isStream" : true,
        "isRestore": true,
        "restoreColumnName": "id",
        "restoreColumnIndex": 0
      }
    },
    "content" : [ {
      "reader": {
        "parameter": {
          "password": "123456",
          "columnTypes": [
            "java.lang.Integer",
            "java.lang.String",
            "java.lang.Integer",
            "java.lang.String"
          ],
          "column": [
            "id",
            "name",
            "content_type_id",
            "codename"
          ],
          "connection": [
            {
              "jdbcUrl": [
                "jdbc:mysql://10.128.122.6:3306/hue?charset=utf8"
              ],
              "table": [
                "auth_permission"
              ]
            }
          ],
          "splitPk": "id",
          "username": "root"
        },
        "name": "mysqlreader"
      },
      "writer" : {
        "parameter" : {
          "producerSettings" : {
            "zookeeper.connect" : "10.128.122.124:2181/kafka",
            "bootstrap.servers" : "10.128.122.124:9092"
          },
          "topic" : "flinkx_test"
        },
        "name" : "kafka11writer",
        "type" : 14
      }
    } ]
  }
}
————————————————————————————————————————————————————————————————————————————————————————
采集结果：

---------------------------------
numWrite                  |  217
last_write_num_0          |  0
conversionErrors          |  0
writeDuration             |  13422
numRead                   |  217
duplicateErrors           |  0
snapshotWrite             |  0
readDuration              |  13561
otherErrors               |  0
byteRead                  |  9590
last_write_location_0     |  0
byteWrite                 |  9590
nullErrors                |  0
nErrors                   |  0
---------------------------------

我在此处打印调试也有结果输出【请见截图】：
![image](https://user-images.githubusercontent.com/13994643/66570868-048b2280-eba1-11e9-8c41-161a2527dce5.png)

**Comment by lawrencehjf** [comment]
> 您好，如下是我自己修改配置的mysql_to_kafaka采集过程，经过调试发现没有出错，也有回显采集结果正常，但是kafka查不到消息，请问我这种方式现在支持么，如果不支持，我需要从哪一步入手来去修改支持，谢谢。
> 线贴出我的配置和采集结果如下：
> 
> ————————————————————————————————————————————
> 配置文件：
> 
> {
> "job" : {
> "setting": {
> "speed": {
> "channel": 1
> },
> "errorLimit": {
> "record": 0,
> "percentage": 0.02
> },
> "restore": {
> "isStream" : true,
> "isRestore": true,
> "restoreColumnName": "id",
> "restoreColumnIndex": 0
> }
> },
> "content" : [ {
> "reader": {
> "parameter": {
> "password": "123456",
> "columnTypes": [
> "java.lang.Integer",
> "java.lang.String",
> "java.lang.Integer",
> "java.lang.String"
> ],
> "column": [
> "id",
> "name",
> "content_type_id",
> "codename"
> ],
> "connection": [
> {
> "jdbcUrl": [
> "jdbc:mysql://10.128.122.6:3306/hue?charset=utf8"
> ],
> "table": [
> "auth_permission"
> ]
> }
> ],
> "splitPk": "id",
> "username": "root"
> },
> "name": "mysqlreader"
> },
> "writer" : {
> "parameter" : {
> "producerSettings" : {
> "zookeeper.connect" : "10.128.122.124:2181/kafka",
> "bootstrap.servers" : "10.128.122.124:9092"
> },
> "topic" : "flinkx_test"
> },
> "name" : "kafka11writer",
> "type" : 14
> }
> } ]
> }
> }
> ————————————————————————————————————————————————————————————————————————————————————————
> 采集结果：
> 
> ## numWrite | 217
> last_write_num_0 | 0
> conversionErrors | 0
> writeDuration | 13422
> numRead | 217
> duplicateErrors | 0
> snapshotWrite | 0
> readDuration | 13561
> otherErrors | 0
> byteRead | 9590
> last_write_location_0 | 0
> byteWrite | 9590
> nullErrors | 0
> nErrors | 0
> 我在此处打印调试也有结果输出【请见截图】：
> ![image](https://user-images.githubusercontent.com/13994643/66570868-048b2280-eba1-11e9-8c41-161a2527dce5.png)

如果支持，请指点下是我配置还是哪里出错导致 write kafka失败，谢谢。

**Comment by yangsishu** [comment]
所有的插件都是可以的

**Comment by yangsishu** [comment]
这个看下kafka的配置有没有问题，这个应该写kafka有问题；kafka的版本要跟你的kafka的集群版本要对应

**Comment by lawrencehjf** [comment]
我断点调试了，发现mysql到kafka需要修改下 kafka11OutputFormat 的代码才可以write成功【详见附图】，所以请帮忙看下，这样处理是否正确，请多多指正，谢谢。

![image](https://user-images.githubusercontent.com/13994643/66797256-c98c4480-ef3c-11e9-8ac6-b388e64131a5.png)

**Comment by lawrencehjf** [comment]
没有写出去得原因，就是此处的if条件，判断过滤掉了从mysql read进来的多条arity情况，直接就停止了程序。

**Comment by lawrencehjf** [comment]
@yangsishu 请问上图红色标注这里，我自己按照理解新加的处理从mysql读进来的数据网 kafka 写，是否合理得当呢，我打算提个 pr，麻烦给指导下看合不合理，可以的话就往咱们master上推一下，而且此处对于读进来 MySQL 的 schema 的处理也是丢失了，目前还不太清楚此处应该怎么保证schema的不丢失，烦请给指点下，谢谢。

**Comment by yangsishu** [comment]
这里是有bug，当时只考虑了binglog数据过来的情况

**Comment by yangsishu** [comment]
可是处理的方式，不能像你现在这样，把row转成string，而是要把row里面的每个属性迭代出来放进map对象里

**Comment by kanata163** [comment]
已支持，请查看相关文档
