### ISSUE TITLE
以yarn模式启动数据同步任务，能否支持指定Yarn的队列提交任务

### ISSUE THREAD

**Issue by LoveXiaoQuan** [DTStack/flinkx#91]
你好：
感谢开源flinkx，使用过程遇到一些问题，望得到回复，谢谢
举例：
flink run -m yarn-cluster -yqu root.queue  -c org.apache.flink.examples.java.wordcount.WordCount  /app/flink-1.7.2/examples/batch/WordCount.jar
这个是命令行参数以单任务yarn模式提交任务，其中 -yqu root.queue 显示指定yarn的资源队列，flinkx能否做到这样的支持

看了ClusterClientFactory这个类的createYarnClient这个方法，发现YarnConfiguration类中的队列名称(DEFAULT_QUEUE_NAME)默认为default,好像没有参数可以修改队列的名称，这个能否支持指定yarn的某个队列来运行flinkx的任务，以做到资源隔离

**Comment by yangsishu** [comment]
可以的

**Comment by kanata163** [comment]
LauncherOptionParser中的queue参数就是用于指定yarn队列
