### ISSUE TITLE
yarn 模式  类型转换错误

### ISSUE THREAD

**Issue by maidou75293** [DTStack/flinkx#97]
cannot assign instance of com.dtstack.flinkx.config.RestoreConfig to field com.dtstack.flinkx.inputformat.RichInputFormat.restoreConfig of type com.dtstack.flinkx.config.RestoreConfig in instance of com.dtstack.flinkx.rdb.inputformat.JdbcInputFormat

**Comment by yangsishu** [comment]
你用的是什么版本
