### ISSUE TITLE
yarn模式 -job参数解析错误

### ISSUE THREAD

**Issue by gj-zhang** [DTStack/flinkx#98]
![image](https://user-images.githubusercontent.com/21170229/67450998-bb7fa780-f651-11e9-810f-e66605668f57.png)

content 是路径， 然后里面调用analyzeUserClasspath 方法里面的DataTransferConfig.parse(content);方法 gson转map异常

**Comment by kanata163** [comment]
已知晓，下个版本中会解决

**Comment by kanata163** [comment]
fix in 1.8.2&1.5.5
