### ISSUE TITLE
standalone直接退出了

### ISSUE THREAD

**Issue by gj-zhang** [DTStack/flinkx#99]
![image](https://user-images.githubusercontent.com/21170229/67452198-0d75fc80-f655-11e9-9958-e69aba98740d.png)

在createClusterClient方法里面判断mode是yarn还是standalone

**Comment by kanata163** [comment]
目前实际上是不支持standalone模式的，请使用local或yarn模式。后续会支持yarn PerJob模式，可能会考虑支持standalone模式。

**Comment by kanata163** [comment]
已支持standalone模式
